#pragma once

#include "../Game/RaceData.h"
#include "../Game/ActorInstance.h"
#ifdef ENABLE_ACCE_SYSTEM
#include "../Render/GrpObjectInstance.h"
#endif
#include "Locale_inc.h"
#include "AffectFlagContainer.h"
#ifdef ENABLE_SHINING_SYSTEM
#include "../Game/ItemData.h"
#endif
class CInstanceBase
{
	public:
		struct SCreateData
		{
			uint8_t	m_bType;
			uint32_t	m_dwStateFlags;
			uint32_t	m_dwEmpireID;
			uint32_t	m_dwGuildID;
			uint32_t	m_dwLevel;
			uint32_t	m_dwVID;
			uint32_t	m_dwRace;
			uint32_t	m_dwMovSpd;
			uint32_t	m_dwAtkSpd;
			int32_t	m_lPosX;
			int32_t	m_lPosY;
			FLOAT	m_fRot;
#ifdef ENABLE_RUNE_SYSTEM
			uint32_t	m_dwRune;
#endif
			uint32_t	m_dwArmor;
			uint32_t	m_dwWeapon;
			uint32_t	m_dwHair;
#ifdef ENABLE_ACCE_SYSTEM
			uint32_t	m_dwAcce;
#endif
			uint32_t	m_dwMountVnum;
#ifdef ENABLE_COSTUME_EFFECT
			uint32_t	m_dwEffectBody;
			uint32_t	m_dwEffectWeapon;
#endif
#ifdef ENABLE_MULTI_LANGUAGE
			uint8_t	m_bLanguage;
#endif
#ifdef ENABLE_SKILL_COLOR_SYSTEM
			uint32_t	m_dwSkillColor[ESkillColorLength::MAX_SKILL_COUNT + MAX_BUFF_COUNT][ESkillColorLength::MAX_EFFECT_COUNT];
#endif

			uint32_t	m_sAlignment;
			uint8_t	m_byPKMode;
			CAffectFlagContainer	m_kAffectFlags;

			std::string m_stName;
			bool	m_isMain;

			SCreateData() :
				m_bType(0),
				m_dwStateFlags(0),
				m_dwEmpireID(0),
				m_dwGuildID(0),
				m_dwLevel(0),
				m_dwVID(0),
				m_dwRace(0),
				m_dwMovSpd(0),
				m_dwAtkSpd(0),
				m_lPosX(0),
				m_lPosY(0),
				m_fRot(0),
#ifdef ENABLE_RUNE_SYSTEM
				m_dwRune(0),
#endif
				m_dwArmor(0),
				m_dwWeapon(0),
				m_dwHair(0),
#ifdef ENABLE_ACCE_SYSTEM
				m_dwAcce(0),
#endif
				m_dwMountVnum(0),
#ifdef ENABLE_COSTUME_EFFECT
				m_dwEffectBody(0),
				m_dwEffectWeapon(0),
#endif
#ifdef ENABLE_MULTI_LANGUAGE
				m_bLanguage(0),
#endif
				m_sAlignment(0),
				m_byPKMode(0),
				m_isMain(false)
			{
#ifdef ENABLE_SKILL_COLOR_SYSTEM
				memset(m_dwSkillColor, 0, sizeof(m_dwSkillColor));
#endif
			}
		};

	public:
		typedef uint32_t TType;

		enum EDirection
		{
			DIR_NORTH,
			DIR_NORTHEAST,
			DIR_EAST,
			DIR_SOUTHEAST,
			DIR_SOUTH,
			DIR_SOUTHWEST,
			DIR_WEST,
			DIR_NORTHWEST,
			DIR_MAX_NUM,
		};

		enum
		{
			FUNC_WAIT,
			FUNC_MOVE,
			FUNC_ATTACK,
			FUNC_COMBO,
			FUNC_MOB_SKILL,
			FUNC_EMOTION,
			FUNC_SKILL = 0x80,
		};

		enum
		{
			AFFECT_YMIR,
			AFFECT_INVISIBILITY,
			AFFECT_SPAWN,

			AFFECT_POISON,
			AFFECT_SLOW,
			AFFECT_STUN,

			AFFECT_DUNGEON_READY,			// ´øÀü¿¡¼­ ÁØºñ »óÅÂ
			AFFECT_SHOW_ALWAYS,				// AFFECT_DUNGEON_UNIQUE ¿¡¼­ º¯°æ(Å¬¶óÀÌ¾ðÆ®¿¡¼­ ÄÃ¸µµÇÁö¾ÊÀ½)

			AFFECT_BUILDING_CONSTRUCTION_SMALL,
			AFFECT_BUILDING_CONSTRUCTION_LARGE,
			AFFECT_BUILDING_UPGRADE,

			AFFECT_MOV_SPEED_POTION,		// 11
			AFFECT_ATT_SPEED_POTION,		// 12

			AFFECT_FISH_MIND,				// 13

			AFFECT_JEONGWI,					// 14 Àü±ÍÈ¥
			AFFECT_GEOMGYEONG,				// 15 °Ë°æ
			AFFECT_CHEONGEUN,				// 16 Ãµ±ÙÃß
			AFFECT_GYEONGGONG,				// 17 °æ°ø¼ú
			AFFECT_EUNHYEONG,				// 18 ÀºÇü¹ý
			AFFECT_GWIGEOM,					// 19 ±Í°Ë
			AFFECT_GONGPO,					// 20 °øÆ÷
			AFFECT_JUMAGAP,					// 21 ÁÖ¸¶°©
			AFFECT_HOSIN,					// 22 È£½Å
			AFFECT_BOHO,					// 23 º¸È£
			AFFECT_KWAESOK,					// 24 Äè¼Ó
		    AFFECT_HEUKSIN,					// 25 Èæ½Å¼öÈ£
			AFFECT_MUYEONG,					// 26 ¹«¿µÁø
			AFFECT_REVIVE_INVISIBILITY,		// 27 ºÎÈ° ¹«Àû
			AFFECT_FIRE,					// 28 Áö¼Ó ºÒ
			AFFECT_GICHEON,					// 29 ±âÃµ ´ë°ø
			AFFECT_JEUNGRYEOK,				// 30 Áõ·Â¼ú
			AFFECT_DASH,					// 31 ´ë½¬
			AFFECT_PABEOP,					// 32 ÆÄ¹ý¼ú
			AFFECT_FALLEN_CHEONGEUN,		// 33 ´Ù¿î ±×·¹ÀÌµå Ãµ±ÙÃß
			AFFECT_POLYMORPH,				// 34 Æú¸®¸ðÇÁ
			AFFECT_WAR_FLAG1,				// 35
			AFFECT_WAR_FLAG2,				// 36
			AFFECT_WAR_FLAG3,				// 37
			AFFECT_CHINA_FIREWORK,			// 38
			AFFECT_PREMIUM_SILVER,
			AFFECT_PREMIUM_GOLD,
			AFFECT_RAMADAN_RING,			// 41 ÃÊ½Â´Þ ¹ÝÁö Âø¿ë Affect

#ifdef ENABLE_MELEY_LAIR_DUNGEON
			AFFECT_STATUE1 = 46,
			AFFECT_STATUE2,
			AFFECT_STATUE3,
			AFFECT_STATUE4,
#endif
#ifdef ENABLE_SOUL_SYSTEM
			AFFECT_SOUL_RED,
			AFFECT_SOUL_BLUE,
			AFFECT_SOUL_MIX,
#endif

			AFFECT_NUM = 64,

			AFFECT_HWAYEOM = AFFECT_GEOMGYEONG,
		};

		enum
		{
			NEW_AFFECT_MOV_SPEED = 200,
			NEW_AFFECT_ATT_SPEED,
			NEW_AFFECT_ATT_GRADE,
			NEW_AFFECT_INVISIBILITY,
			NEW_AFFECT_STR,
			NEW_AFFECT_DEX,
			NEW_AFFECT_CON,
			NEW_AFFECT_INT,
			NEW_AFFECT_FISH_MIND_PILL,
			NEW_AFFECT_POISON,
			NEW_AFFECT_STUN,
			NEW_AFFECT_SLOW,
			NEW_AFFECT_DUNGEON_READY,
			NEW_AFFECT_DUNGEON_UNIQUE,
			NEW_AFFECT_BUILDING,
			NEW_AFFECT_REVIVE_INVISIBLE,
			NEW_AFFECT_FIRE,
			NEW_AFFECT_CAST_SPEED,
			NEW_AFFECT_HP_RECOVER_CONTINUE,
			NEW_AFFECT_SP_RECOVER_CONTINUE,
			NEW_AFFECT_POLYMORPH,
			NEW_AFFECT_MOUNT,
			NEW_AFFECT_WAR_FLAG,
			NEW_AFFECT_BLOCK_CHAT,
			NEW_AFFECT_CHINA_FIREWORK,
			NEW_AFFECT_BOW_DISTANCE,
			NEW_AFFECT_DEF_GRADE,

			NEW_AFFECT_PET,
			NEW_AFFECT_RAMADAN_ABILITY = 300,
			NEW_AFFECT_RAMADAN_RING = 301,
			NEW_AFFECT_NOG_POCKET_ABILITY = 302,
			NEW_AFFECT_HOLLY_STONE_POWER = 303,
#ifdef ENABLE_SOUL_SYSTEM
			NEW_AFFECT_SOUL_RED = 304,
			NEW_AFFECT_SOUL_BLUE = 305,
#endif
			NEW_AFFECT_EXP_BONUS = 500,
			NEW_AFFECT_ITEM_BONUS = 501,
			NEW_AFFECT_SAFEBOX = 502,
			NEW_AFFECT_AUTOLOOT = 503,
			NEW_AFFECT_FISH_MIND = 504,
			NEW_AFFECT_MARRIAGE_FAST = 505,
			NEW_AFFECT_GOLD_BONUS = 506,
			NEW_AFFECT_MALL = 510,
			NEW_AFFECT_NO_DEATH_PENALTY = 511,
			NEW_AFFECT_SKILL_BOOK_BONUS = 512,
			NEW_AFFECT_SKILL_BOOK_NO_DELAY = 513,
			NEW_AFFECT_HAIR	= 514,
			NEW_AFFECT_COLLECT = 515,
			NEW_AFFECT_EXP_BONUS_EURO_FREE = 516,
			NEW_AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
			NEW_AFFECT_UNIQUE_ABILITY = 518,
			NEW_AFFECT_CUBE_1,
			NEW_AFFECT_CUBE_2,
			NEW_AFFECT_CUBE_3,
			NEW_AFFECT_CUBE_4,
			NEW_AFFECT_CUBE_5,
			NEW_AFFECT_CUBE_6,
			NEW_AFFECT_CUBE_7,
			NEW_AFFECT_CUBE_8,
			NEW_AFFECT_CUBE_9,
			NEW_AFFECT_CUBE_10,
			NEW_AFFECT_CUBE_11,
			NEW_AFFECT_CUBE_12,
			NEW_AFFECT_BLEND,
			NEW_AFFECT_HORSE_NAME,
			NEW_AFFECT_MOUNT_BONUS,
			NEW_AFFECT_AUTO_HP_RECOVERY = 534,
			NEW_AFFECT_AUTO_SP_RECOVERY = 535,
#ifdef ENABLE_NEW_USE_POTION
			NEW_AFFECT_AUTO_HP_RECOVERY2 = 536,
			NEW_AFFECT_AUTO_SP_RECOVERY2 = 537,
#endif
#ifdef ENABLE_BATTLE_PASS
			NEW_AFFECT_BATTLE_PASS = 538,
#ifdef ENABLE_FREE_PASS_RAZOR93
			NEW_AFFECT_BATTLE_PASS_BOOST = 1012,
#endif
#endif
#ifdef NEW_PET_SYSTEM
			NEW_AFFECT_NEW_PET = 539,
#endif
			NEW_AFFECT_DRAGON_SOUL_QUALIFIED = 540,
			NEW_AFFECT_DRAGON_SOUL_DECK1 = 541,
			NEW_AFFECT_DRAGON_SOUL_DECK2 = 542,


			ALIGNMENT_BONUS_1 = 543,
			ALIGNMENT_BONUS_2 = 544,
			ALIGNMENT_BONUS_3 = 545,
			ALIGNMENT_BONUS_4 = 546,
			ALIGNMENT_BONUS_5 = 547,
			ALIGNMENT_BONUS_6 = 548,
			ALIGNMENT_BONUS_7 = 549,
			ALIGNMENT_BONUS_8 = 550,
			ALIGNMENT_BONUS_9 = 551,
			ALIGNMENT_BONUS_10 = 552,
			ALIGNMENT_BONUS_11 = 553,
			ALIGNMENT_BONUS_12 = 554,
			ALIGNMENT_BONUS_13 = 555,
			ALIGNMENT_BONUS_14 = 556,
			ALIGNMENT_BONUS_15 = 557,
			ALIGNMENT_BONUS_16 = 558,





#ifdef ENABLE_DS_SET
			NEW_AFFECT_DS_SET = 563,
			NEW_AFFECT_DS_BNS1 = 564,
			NEW_AFFECT_DS_BNS2 = 565,
			NEW_AFFECT_DS_BNS3 = 566,
#endif
#ifdef ENABLE_NEW_USE_POTION
			AFFECT_NEW_POTION1 = 567,
			AFFECT_NEW_POTION2 = 568,
			AFFECT_NEW_POTION3 = 569,
			AFFECT_NEW_POTION4 = 570,
			AFFECT_NEW_POTION5 = 571,
			AFFECT_NEW_POTION6 = 572,
			AFFECT_NEW_POTION7 = 573,
			AFFECT_NEW_POTION8 = 574,
			AFFECT_NEW_POTION9 = 575,
			AFFECT_NEW_POTION10 = 576,
			AFFECT_NEW_POTION11 = 577,
			AFFECT_NEW_POTION12 = 578,
			AFFECT_NEW_POTION13 = 579,
			AFFECT_NEW_POTION14 = 580,
			AFFECT_NEW_POTION15 = 581,
			AFFECT_NEW_POTION16 = 582,
			AFFECT_NEW_POTION17 = 583,
			AFFECT_NEW_POTION18 = 584,
			AFFECT_NEW_POTION19 = 585,
			AFFECT_NEW_POTION20 = 586,
#endif
#ifdef ENABLE_RECALL
			NEW_AFFECT_RECALL1 = 587,
#ifdef NEW_PET_SYSTEM
			NEW_AFFECT_RECALL2 = 589,
#endif
#endif
#ifdef ENABLE_NEW_USE_POTION
			AFFECT_NEW_POTION21 = 590,
			AFFECT_NEW_POTION22 = 591,
			AFFECT_NEW_POTION23 = 592,
			AFFECT_NEW_POTION24 = 593,
			AFFECT_NEW_POTION25 = 594,
			AFFECT_NEW_POTION26 = 595,
			AFFECT_NEW_POTION27 = 596,
			AFFECT_NEW_POTION28 = 597,
			AFFECT_NEW_POTION29 = 598,
			AFFECT_NEW_POTION30 = 599,
			AFFECT_NEW_POTION31 = 600,
#endif
#ifdef ENABLE_VOTE_FOR_BONUS
			AFFECT_VOTEFORBONUS = 702,
#endif
#ifdef ENABLE_VOTE4BUFF
				NEW_AFFECT_VOTE4BUFF = 809,
#endif
#ifdef ENABLE_RUNE_SYSTEM
			AFFECT_RUNE1 = 996,
			AFFECT_RUNE2,
#endif
#ifdef ENABLE_BLOCK_MULTIFARM
			AFFECT_DROP_BLOCK = 998,
			AFFECT_DROP_UNBLOCK,
#endif
#ifdef __AUTO_QUQUE_ATTACK__
			NEW_AFFECT_AUTO_METIN_FARM = 706,
#endif
			NEW_AFFECT_QUEST_START_IDX   = 1000,
#ifdef AFFECT_EXP_ITEM_RAZOR93
			AFFECT_EXP_RAZOR93 = 1100,
			AFFECT_ITEM_RAZOR93 = 1101,
			AFFECT_METIN_RAZOR93 = 1102,
#endif // AFFECT_EXP_ITEM_RAZOR93

		};

		enum
		{
			STONE_SMOKE1 = 0,	// 99%
			STONE_SMOKE2 = 1,	// 85%
			STONE_SMOKE3 = 2,	// 80%
			STONE_SMOKE4 = 3,	// 60%
			STONE_SMOKE5 = 4,	// 45%
			STONE_SMOKE6 = 5,	// 40%
			STONE_SMOKE7 = 6,	// 20%
			STONE_SMOKE8 = 7,	// 10%
			STONE_SMOKE_NUM = 4,
		};

		enum EBuildingAffect
		{
			BUILDING_CONSTRUCTION_SMALL = 0,
			BUILDING_CONSTRUCTION_LARGE = 1,
			BUILDING_UPGRADE = 2,
		};

		enum
		{
			WEAPON_DUALHAND,
			WEAPON_ONEHAND,
			WEAPON_TWOHAND,
			WEAPON_NUM,
		};

		enum
		{
			EMPIRE_NONE,
			EMPIRE_A,
			EMPIRE_B,
			EMPIRE_C,
			EMPIRE_NUM,
		};

		enum
		{
			NAMECOLOR_MOB,
			NAMECOLOR_NPC,
			NAMECOLOR_PC,
			NAMECOLOR_PC_END = NAMECOLOR_PC + EMPIRE_NUM,
			NAMECOLOR_NORMAL_MOB,
			NAMECOLOR_NORMAL_NPC,
			NAMECOLOR_NORMAL_PC,
			NAMECOLOR_NORMAL_PC_END = NAMECOLOR_NORMAL_PC + EMPIRE_NUM,
			NAMECOLOR_EMPIRE_MOB,
			NAMECOLOR_EMPIRE_NPC,
			NAMECOLOR_EMPIRE_PC,
			NAMECOLOR_EMPIRE_PC_END = NAMECOLOR_EMPIRE_PC + EMPIRE_NUM,
			NAMECOLOR_FUNC,
			NAMECOLOR_PK,
			NAMECOLOR_PVP,
			NAMECOLOR_PARTY,
			NAMECOLOR_WARP,
			NAMECOLOR_WAYPOINT,
			NAMECOLOR_EXTRA = NAMECOLOR_FUNC + 10,
			NAMECOLOR_NUM = NAMECOLOR_EXTRA + 10,
		};

		enum
		{
			ALIGNMENT_TYPE_WHITE,
			ALIGNMENT_TYPE_NORMAL,
			ALIGNMENT_TYPE_DARK,
		};

		enum
		{
			EMOTICON_EXCLAMATION	= 1,
			EMOTICON_FISH			= 11,
			EMOTICON_NUM			= 128,

			TITLE_NUM				= 21,
		//	TITLE_NONE				= 4,
		};

		enum	//¾Æ·¡ ¹øÈ£°¡ ¹Ù²î¸é registerEffect ÂÊµµ ¹Ù²Ù¾î Áà¾ß ÇÑ´Ù.
		{
			EFFECT_REFINED_NONE,
			EFFECT_SWORD_REFINED7,
			EFFECT_SWORD_REFINED8,
			EFFECT_SWORD_REFINED9,
			EFFECT_BOW_REFINED7,
			EFFECT_BOW_REFINED8,
			EFFECT_BOW_REFINED9,
			EFFECT_FANBELL_REFINED7,
			EFFECT_FANBELL_REFINED8,
			EFFECT_FANBELL_REFINED9,
			EFFECT_SMALLSWORD_REFINED7,
			EFFECT_SMALLSWORD_REFINED8,
			EFFECT_SMALLSWORD_REFINED9,
			EFFECT_SMALLSWORD_REFINED7_LEFT,
			EFFECT_SMALLSWORD_REFINED8_LEFT,
			EFFECT_SMALLSWORD_REFINED9_LEFT,
			EFFECT_BODYARMOR_REFINED7,
			EFFECT_BODYARMOR_REFINED8,
			EFFECT_BODYARMOR_REFINED9,
			EFFECT_BODYARMOR_SPECIAL,	// °©¿Ê 4-2-1
			EFFECT_BODYARMOR_SPECIAL2,	// °©¿Ê 4-2-2
//#ifdef ENABLE_LVL115_ARMOR_EFFECT
			EFFECT_BODYARMOR_SPECIAL3,	// 5-1
//#endif
//#ifdef __ENABLE_NEW_EFFECT_CIANITE__
			EFFECT_BODYARMOR_CIANITE1 = 26,
			EFFECT_BODYARMOR_CIANITE2 = 27,
			EFFECT_BODYARMOR_CIANITE3 = 28,
			EFFECT_BODYARMOR_CIANITE4 = 29,
//#endif
//#ifdef __ENABLE_NEW_EFFECT_CIANITE_WEAPON__
			EFFECT_SWORD_CIANITE_SPECIAL1 = 30,  // EFFECT SPECIAL1,2,3,4 FOR CIANITE SWORD & LAMA
			EFFECT_SWORD_CIANITE_SPECIAL2 = 31,
			EFFECT_SWORD_CIANITE_SPECIAL3 = 32,
			EFFECT_SWORD_CIANITE_SPECIAL4 = 33,
			EFFECT_2HAND_CIANITE_SPECIAL1 = 34,  // EFFECT SPECIAL1,2,3,4 FOR CIANITE 2HAND
			EFFECT_2HAND_CIANITE_SPECIAL2 = 35,
			EFFECT_2HAND_CIANITE_SPECIAL3 = 36,
			EFFECT_2HAND_CIANITE_SPECIAL4 = 37,
			EFFECT_BELL_CIANITE_SPECIAL1 = 38,  // EFFECT SPECIAL1,2,3,4 FOR CIANITE BELL
			EFFECT_BELL_CIANITE_SPECIAL2 = 39,
			EFFECT_BELL_CIANITE_SPECIAL3 = 40,
			EFFECT_BELL_CIANITE_SPECIAL4 = 41,
			EFFECT_FAN_CIANITE_SPECIAL1 = 42,  // EFFECT SPECIAL1,2,3,4 FOR CIANITE FAN
			EFFECT_FAN_CIANITE_SPECIAL2 = 43,
			EFFECT_FAN_CIANITE_SPECIAL3 = 44,
			EFFECT_FAN_CIANITE_SPECIAL4 = 45,
			EFFECT_BOW_CIANITE_SPECIAL1 = 46,  // EFFECT SPECIAL1,2,3,4 FOR CIANITE BOW
			EFFECT_BOW_CIANITE_SPECIAL2 = 47,
			EFFECT_BOW_CIANITE_SPECIAL3 = 48,
			EFFECT_BOW_CIANITE_SPECIAL4 = 49,
			EFFECT_DAGGER_CIANITE_SPECIAL1 = 50,  // EFFECT SPECIAL1,2,3,4 FOR CIANITE DAGGER
			EFFECT_DAGGER_CIANITE_SPECIAL2 = 51,
			EFFECT_DAGGER_CIANITE_SPECIAL3 = 52,
			EFFECT_DAGGER_CIANITE_SPECIAL4 = 53,
			EFFECT_DAGGER_CIANITE_SPECIAL1_LEFT = 54,
			EFFECT_DAGGER_CIANITE_SPECIAL2_LEFT = 55,
			EFFECT_DAGGER_CIANITE_SPECIAL3_LEFT = 56,
			EFFECT_DAGGER_CIANITE_SPECIAL4_LEFT = 57,
//#endif
//#ifdef __ENABLE_NEW_EFFECT_STOLE__
			EFFECT_STOLA_GREEN = 68,
			EFFECT_STOLA_BLACK = 69,
			EFFECT_STOLA_ORANGE = 70,
			EFFECT_STOLA_PURPLE = 71,
			EFFECT_STOLA_RED = 72,
			EFFECT_STOLA_WHITE = 73,
			EFFECT_STOLA_YELLOW = 74,
//#endif
//#ifdef ENABLE_ACCE_SYSTEM
			EFFECT_ACCE = 75,
//#endif
//#ifdef ENABLE_COSTUME_EFFECT
			EFFECT_BODY_COSTUME1 = 76,
			EFFECT_WEAPON_COSTUME1_SWORD = 77,
			EFFECT_WEAPON_COSTUME1_TWO_HANDED = 78,
			EFFECT_WEAPON_COSTUME1_DAGGER = 79,
			EFFECT_WEAPON_COSTUME1_BOW = 80,
			EFFECT_WEAPON_COSTUME1_BELL = 81,
			EFFECT_WEAPON_COSTUME1_FAN = 82,
			EFFECT_WEAPON_COSTUME1_DAGGER_LEFT = 83,
//#endif
//#ifdef __ENABLE_NEW_EFFECT_STOLE__
			EFFECT_STOLA_1 = 84,
			EFFECT_STOLA_2 = 85,
			EFFECT_STOLA_3 = 86,
			EFFECT_STOLA_4 = 87,
			EFFECT_STOLA_5 = 88,
			EFFECT_STOLA_6 = 89,
			EFFECT_STOLA_7 = 90,
//#endif
//#ifdef __ENABLE_NEW_EFFECT_ZODIACO__
			EFFECT_BODYARMOR_ZODIACO = 91,
			EFFECT_BODYARMOR_ZODIACO2 = 92,
			EFFECT_BODYARMOR_ZODIACO3 = 93,
			EFFECT_BODYARMOR_ZODIACO4 = 94,
//#endif
//#ifdef __ENABLE_NEW_EFFECT_ZODIACO_WEAPON__
			EFFECT_SWORD_ZODIACO_SPECIAL1 = 95,  // EFFECT SPECIAL1,2,3,4 FOR ZODIACO SWORD & LAMA
			EFFECT_SWORD_ZODIACO_SPECIAL2 = 96,
			EFFECT_SWORD_ZODIACO_SPECIAL3 = 97,
			EFFECT_SWORD_ZODIACO_SPECIAL4 = 98,
			EFFECT_SPEAR_ZODIACO_SPECIAL1 = 99,  // EFFECT SPECIAL1,2,3,4 FOR ZODIACO SPEAR
			EFFECT_SPEAR_ZODIACO_SPECIAL2 = 100,
			EFFECT_SPEAR_ZODIACO_SPECIAL3 = 101,
			EFFECT_SPEAR_ZODIACO_SPECIAL4 = 102,
			EFFECT_BELL_ZODIACO_SPECIAL1 = 103,  // EFFECT SPECIAL1,2,3,4 FOR ZODIACO BELL
			EFFECT_BELL_ZODIACO_SPECIAL2 = 104,
			EFFECT_BELL_ZODIACO_SPECIAL3 = 105,
			EFFECT_BELL_ZODIACO_SPECIAL4 = 106,
			EFFECT_FAN_ZODIACO_SPECIAL1 = 107,  // EFFECT SPECIAL1,2,3,4 FOR ZODIACO FAN
			EFFECT_FAN_ZODIACO_SPECIAL2 = 108,
			EFFECT_FAN_ZODIACO_SPECIAL3 = 109,
			EFFECT_FAN_ZODIACO_SPECIAL4 = 110,
			EFFECT_BOW_ZODIACO_SPECIAL1 = 111,  // EFFECT SPECIAL1,2,3,4 FOR ZODIACO BOW
			EFFECT_BOW_ZODIACO_SPECIAL2 = 112,
			EFFECT_BOW_ZODIACO_SPECIAL3 = 113,
			EFFECT_BOW_ZODIACO_SPECIAL4 = 114,
			EFFECT_KNIFE_ZODIACO_SPECIAL1 = 115,  // EFFECT SPECIAL1,2,3,4 FOR ZODIACO KNIFE
			EFFECT_KNIFE_ZODIACO_SPECIAL2 = 116,
			EFFECT_KNIFE_ZODIACO_SPECIAL3 = 117,
			EFFECT_KNIFE_ZODIACO_SPECIAL4 = 118,
			EFFECT_KNIFE_ZODIACO_SPECIAL1_LEFT = 119,
			EFFECT_KNIFE_ZODIACO_SPECIAL2_LEFT = 120,
			EFFECT_KNIFE_ZODIACO_SPECIAL3_LEFT = 121,
			EFFECT_KNIFE_ZODIACO_SPECIAL4_LEFT = 122,
//#endif
//#ifdef __ENABLE_NEW_EFFECT_ZODIACO1__
			EFFECT_BODYARMOR_ZODIACO1 = 123,
//#endif
//#ifdef __ENABLE_NEW_EFFECT_ZODIACO_WEAPON1__
			EFFECT_SWORD_ZODIACO_WEAPON1 = 124,
			EFFECT_SPEAR_ZODIACO_WEAPON1 = 125,
			EFFECT_BELL_ZODIACO_WEAPON1 = 126,
			EFFECT_FAN_ZODIACO_WEAPON1 = 127,
			EFFECT_BOW_ZODIACO_WEAPON1 = 128,
			EFFECT_KNIFE_ZODIACO_WEAPON1 = 129,
			EFFECT_KNIFE_ZODIACO_WEAPON1_LEFT = 130,
//#endif
//#ifdef ENABLE_COSTUME_EFFECT
			EFFECT_BODY_COSTUME2 = 131,
			EFFECT_WEAPON_COSTUME2_SWORD = 132,
			EFFECT_WEAPON_COSTUME2_TWO_HANDED = 133,
			EFFECT_WEAPON_COSTUME2_DAGGER = 134,
			EFFECT_WEAPON_COSTUME2_BOW = 135,
			EFFECT_WEAPON_COSTUME2_BELL = 136,
			EFFECT_WEAPON_COSTUME2_FAN = 137,
			EFFECT_WEAPON_COSTUME2_DAGGER_LEFT = 138,
			EFFECT_BODY_COSTUME3 = 139,
			EFFECT_WEAPON_COSTUME3_SWORD = 140,
			EFFECT_WEAPON_COSTUME3_TWO_HANDED = 141,
			EFFECT_WEAPON_COSTUME3_DAGGER = 142,
			EFFECT_WEAPON_COSTUME3_BOW = 143,
			EFFECT_WEAPON_COSTUME3_BELL = 144,
			EFFECT_WEAPON_COSTUME3_FAN = 145,
			EFFECT_WEAPON_COSTUME3_DAGGER_LEFT = 146,
			EFFECT_BODY_COSTUME4 = 147,
			EFFECT_WEAPON_COSTUME4_SWORD = 148,
			EFFECT_WEAPON_COSTUME4_TWO_HANDED = 149,
			EFFECT_WEAPON_COSTUME4_DAGGER = 150,
			EFFECT_WEAPON_COSTUME4_BOW = 151,
			EFFECT_WEAPON_COSTUME4_BELL = 152,
			EFFECT_WEAPON_COSTUME4_FAN = 153,
			EFFECT_WEAPON_COSTUME4_DAGGER_LEFT = 154,
			EFFECT_BODY_COSTUME5 = 155,
			EFFECT_WEAPON_COSTUME5_SWORD = 156,
			EFFECT_WEAPON_COSTUME5_TWO_HANDED = 157,
			EFFECT_WEAPON_COSTUME5_DAGGER = 158,
			EFFECT_WEAPON_COSTUME5_BOW = 159,
			EFFECT_WEAPON_COSTUME5_BELL = 160,
			EFFECT_WEAPON_COSTUME5_FAN = 161,
			EFFECT_WEAPON_COSTUME5_DAGGER_LEFT = 162,
			EFFECT_BODY_COSTUME6 = 163,
			EFFECT_WEAPON_COSTUME6_SWORD = 164,
			EFFECT_WEAPON_COSTUME6_TWO_HANDED = 165,
			EFFECT_WEAPON_COSTUME6_DAGGER = 166,
			EFFECT_WEAPON_COSTUME6_BOW = 167,
			EFFECT_WEAPON_COSTUME6_BELL = 168,
			EFFECT_WEAPON_COSTUME6_FAN = 169,
			EFFECT_WEAPON_COSTUME6_DAGGER_LEFT = 170,
			EFFECT_BODY_COSTUME7 = 171,
			EFFECT_WEAPON_COSTUME7_SWORD = 172,
			EFFECT_WEAPON_COSTUME7_TWO_HANDED = 173,
			EFFECT_WEAPON_COSTUME7_DAGGER = 174,
			EFFECT_WEAPON_COSTUME7_BOW = 175,
			EFFECT_WEAPON_COSTUME7_BELL = 176,
			EFFECT_WEAPON_COSTUME7_FAN = 177,
			EFFECT_WEAPON_COSTUME7_DAGGER_LEFT = 178,
			EFFECT_BODY_COSTUME8 = 179,
			EFFECT_WEAPON_COSTUME8_SWORD = 180,
			EFFECT_WEAPON_COSTUME8_TWO_HANDED = 181,
			EFFECT_WEAPON_COSTUME8_DAGGER = 182,
			EFFECT_WEAPON_COSTUME8_BOW = 183,
			EFFECT_WEAPON_COSTUME8_BELL = 184,
			EFFECT_WEAPON_COSTUME8_FAN = 185,
			EFFECT_WEAPON_COSTUME8_DAGGER_LEFT = 186,
			EFFECT_BODY_COSTUME9 = 187,
			EFFECT_WEAPON_COSTUME9_SWORD = 188,
			EFFECT_WEAPON_COSTUME9_TWO_HANDED = 189,
			EFFECT_WEAPON_COSTUME9_DAGGER = 190,
			EFFECT_WEAPON_COSTUME9_BOW = 191,
			EFFECT_WEAPON_COSTUME9_BELL = 192,
			EFFECT_WEAPON_COSTUME9_FAN = 193,
			EFFECT_WEAPON_COSTUME9_DAGGER_LEFT = 194,
			EFFECT_BODY_COSTUME10 = 195,
			EFFECT_WEAPON_COSTUME10_SWORD = 196,
			EFFECT_WEAPON_COSTUME10_TWO_HANDED = 197,
			EFFECT_WEAPON_COSTUME10_DAGGER = 198,
			EFFECT_WEAPON_COSTUME10_BOW = 199,
			EFFECT_WEAPON_COSTUME10_BELL = 200,
			EFFECT_WEAPON_COSTUME10_FAN = 201,
			EFFECT_WEAPON_COSTUME10_DAGGER_LEFT = 202,
			EFFECT_BODY_COSTUME11 = 203,
			EFFECT_WEAPON_COSTUME11_SWORD = 204,
			EFFECT_WEAPON_COSTUME11_TWO_HANDED = 205,
			EFFECT_WEAPON_COSTUME11_DAGGER = 206,
			EFFECT_WEAPON_COSTUME11_BOW = 207,
			EFFECT_WEAPON_COSTUME11_BELL = 208,
			EFFECT_WEAPON_COSTUME11_FAN = 209,
			EFFECT_WEAPON_COSTUME11_DAGGER_LEFT = 210,
			EFFECT_BODY_COSTUME12 = 211,
			EFFECT_WEAPON_COSTUME12_SWORD = 212,
			EFFECT_WEAPON_COSTUME12_TWO_HANDED = 213,
			EFFECT_WEAPON_COSTUME12_DAGGER = 214,
			EFFECT_WEAPON_COSTUME12_BOW = 215,
			EFFECT_WEAPON_COSTUME12_BELL = 216,
			EFFECT_WEAPON_COSTUME12_FAN = 217,
			EFFECT_WEAPON_COSTUME12_DAGGER_LEFT = 218,
//#endif
//#ifdef ENABLE_BUGFIX_EFFECT_FAN
			EFFECT_FANBELL_LEFT_REFINED7 = 219,
			EFFECT_FANBELL_LEFT_REFINED8,
			EFFECT_FANBELL_LEFT_REFINED9,
			EFFECT_FAN_CIANITE_LEFT_SPECIAL1,
			EFFECT_FAN_CIANITE_LEFT_SPECIAL2,
			EFFECT_FAN_CIANITE_LEFT_SPECIAL3,
			EFFECT_FAN_CIANITE_LEFT_SPECIAL4,
			EFFECT_FAN_ZODIACO_LEFT_SPECIAL1,
			EFFECT_FAN_ZODIACO_LEFT_SPECIAL2,
			EFFECT_FAN_ZODIACO_LEFT_SPECIAL3,
			EFFECT_FAN_ZODIACO_LEFT_SPECIAL4,
			EFFECT_FAN_ZODIACO_LEFT_WEAPON1,
//#ifdef ENABLE_COSTUME_EFFECT
			EFFECT_WEAPON_COSTUME1_FAN_LEFT,
			EFFECT_WEAPON_COSTUME2_FAN_LEFT,
			EFFECT_WEAPON_COSTUME3_FAN_LEFT,
			EFFECT_WEAPON_COSTUME4_FAN_LEFT,
			EFFECT_WEAPON_COSTUME5_FAN_LEFT,
			EFFECT_WEAPON_COSTUME6_FAN_LEFT,
			EFFECT_WEAPON_COSTUME7_FAN_LEFT,
			EFFECT_WEAPON_COSTUME8_FAN_LEFT,
			EFFECT_WEAPON_COSTUME9_FAN_LEFT,
			EFFECT_WEAPON_COSTUME10_FAN_LEFT,
			EFFECT_WEAPON_COSTUME11_FAN_LEFT,
			EFFECT_WEAPON_COSTUME12_FAN_LEFT,
			EFFECT_WEAPON_COSTUME1_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME1_FAN_LEFT,
			EFFECT_WEAPON_COSTUME2_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME2_FAN_LEFT,
			EFFECT_WEAPON_COSTUME3_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME3_FAN_LEFT,
			EFFECT_WEAPON_COSTUME4_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME4_FAN_LEFT,
			EFFECT_WEAPON_COSTUME5_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME5_FAN_LEFT,
			EFFECT_WEAPON_COSTUME6_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME6_FAN_LEFT,
			EFFECT_WEAPON_COSTUME7_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME7_FAN_LEFT,
			EFFECT_WEAPON_COSTUME8_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME8_FAN_LEFT,
			EFFECT_WEAPON_COSTUME9_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME9_FAN_LEFT,
			EFFECT_WEAPON_COSTUME10_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME10_FAN_LEFT,
			EFFECT_WEAPON_COSTUME11_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME11_FAN_LEFT,
			EFFECT_WEAPON_COSTUME12_FAN_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME12_FAN_LEFT,
//#endif
//#endif
//#ifdef ENABLE_COSTUME_EFFECT
			EFFECT_WEAPON_COSTUME1_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME1_DAGGER,
			EFFECT_WEAPON_COSTUME1_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME1_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME1_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME1_FAN,
			EFFECT_WEAPON_COSTUME2_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME2_DAGGER,
			EFFECT_WEAPON_COSTUME2_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME2_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME2_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME2_FAN,
			EFFECT_WEAPON_COSTUME3_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME3_DAGGER,
			EFFECT_WEAPON_COSTUME3_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME3_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME3_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME3_FAN,
			EFFECT_WEAPON_COSTUME4_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME4_DAGGER,
			EFFECT_WEAPON_COSTUME4_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME4_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME4_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME4_FAN,
			EFFECT_WEAPON_COSTUME5_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME5_DAGGER,
			EFFECT_WEAPON_COSTUME5_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME5_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME5_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME5_FAN,
			EFFECT_WEAPON_COSTUME6_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME6_DAGGER,
			EFFECT_WEAPON_COSTUME6_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME6_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME6_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME6_FAN,
			EFFECT_WEAPON_COSTUME7_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME7_DAGGER,
			EFFECT_WEAPON_COSTUME7_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME7_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME7_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME7_FAN,
			EFFECT_WEAPON_COSTUME8_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME8_DAGGER,
			EFFECT_WEAPON_COSTUME8_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME8_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME8_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME8_FAN,
			EFFECT_WEAPON_COSTUME9_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME9_DAGGER,
			EFFECT_WEAPON_COSTUME9_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME9_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME9_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME9_FAN,
			EFFECT_WEAPON_COSTUME10_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME10_DAGGER,
			EFFECT_WEAPON_COSTUME10_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME10_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME10_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME10_FAN,
			EFFECT_WEAPON_COSTUME11_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME11_DAGGER,
			EFFECT_WEAPON_COSTUME11_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME11_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME11_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME11_FAN,
			EFFECT_WEAPON_COSTUME12_DAGGER_SPECIAL = 500 + EFFECT_WEAPON_COSTUME12_DAGGER,
			EFFECT_WEAPON_COSTUME12_DAGGER_SPECIAL_LEFT = 500 + EFFECT_WEAPON_COSTUME12_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME12_FAN_SPECIAL = 500 + EFFECT_WEAPON_COSTUME12_FAN,
//#endif
			EFFECT_HALLOWEEN_2021_WING = 743,
			EFFECT_HALLOWEEN_2021_SWORD,
			EFFECT_HALLOWEEN_2021_DAGGER_RIGHT,
			EFFECT_HALLOWEEN_2021_DAGGER_LEFT,
			EFFECT_HALLOWEEN_2021_BOW,
			EFFECT_HALLOWEEN_2021_TWOHAND,
			EFFECT_HALLOWEEN_2021_BELL,
			EFFECT_HALLOWEEN_2021_FAN,
			EFFECT_HALLOWEEN_2021_COSTUME,
			EFFECT_PATCH3_COSTUME1_WING = 752,
			EFFECT_PATCH3_COSTUME1_SWORD,
			EFFECT_PATCH3_COSTUME1_DAGGER_RIGHT,
			EFFECT_PATCH3_COSTUME1_DAGGER_LEFT,
			EFFECT_PATCH3_COSTUME1_BOW,
			EFFECT_PATCH3_COSTUME1_TWOHAND,
			EFFECT_PATCH3_COSTUME1_BELL,
			EFFECT_PATCH3_COSTUME1_FAN,
			EFFECT_PATCH3_COSTUME1_COSTUME,
			EFFECT_PATCH3_COSTUME2_WING = 761,
			EFFECT_PATCH3_COSTUME2_SWORD,
			EFFECT_PATCH3_COSTUME2_DAGGER_RIGHT,
			EFFECT_PATCH3_COSTUME2_DAGGER_LEFT,
			EFFECT_PATCH3_COSTUME2_BOW,
			EFFECT_PATCH3_COSTUME2_TWOHAND,
			EFFECT_PATCH3_COSTUME2_BELL,
			EFFECT_PATCH3_COSTUME2_FAN,
			EFFECT_PATCH3_COSTUME2_COSTUME,
			EFFECT_HALLOWEEN_2021_FAN_LEFT,
			EFFECT_PATCH3_COSTUME3_WING = 771,
			EFFECT_PATCH3_COSTUME3_SWORD,
			EFFECT_PATCH3_COSTUME3_DAGGER_RIGHT,
			EFFECT_PATCH3_COSTUME3_DAGGER_LEFT,
			EFFECT_PATCH3_COSTUME3_BOW,
			EFFECT_PATCH3_COSTUME3_TWOHAND,
			EFFECT_PATCH3_COSTUME3_BELL,
			EFFECT_PATCH3_COSTUME3_FAN,
			EFFECT_PATCH3_COSTUME3_COSTUME,
			EFFECT_PATCH3_COSTUME3_FAN_LEFT,
			EFFECT_PATCH4_COSTUME_M = 781,
			EFFECT_PATCH4_COSTUME_M_1,
			EFFECT_PATCH4_COSTUME_M_2,
			EFFECT_PATCH4_COSTUME_F_1,
			EFFECT_PATCH4_COSTUME_F_2,
			EFFECT_PATCH4_SWORD,
			EFFECT_PATCH4_DAGGER_RIGHT,
			EFFECT_PATCH4_DAGGER_LEFT,
			EFFECT_PATCH4_BOW,
			EFFECT_PATCH4_TWOHAND,
			EFFECT_PATCH4_BELL,
			EFFECT_PATCH4_FAN,
			EFFECT_PATCH4_FAN_LEFT,
			EFFECT_BODY_COSTUME13 = 794,
			EFFECT_WEAPON_COSTUME13_SWORD,
			EFFECT_WEAPON_COSTUME13_TWO_HANDED,
			EFFECT_WEAPON_COSTUME13_DAGGER,
			EFFECT_WEAPON_COSTUME13_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME13_BOW,
			EFFECT_WEAPON_COSTUME13_BELL,
			EFFECT_WEAPON_COSTUME13_FAN,
			EFFECT_WEAPON_COSTUME13_FAN_LEFT,
			EFFECT_BODY_COSTUME14 = 803,
			EFFECT_WEAPON_COSTUME14_SWORD,
			EFFECT_WEAPON_COSTUME14_DAGGER,
			EFFECT_WEAPON_COSTUME14_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME14_BOW,
			EFFECT_WEAPON_COSTUME14_TWO_HANDED,
			EFFECT_WEAPON_COSTUME14_BELL,
			EFFECT_WEAPON_COSTUME14_FAN,
			EFFECT_WEAPON_COSTUME14_FAN_LEFT,
			EFFECT_WING_COSTUME15 = 812,
			EFFECT_BODY_COSTUME16 = 813,
			EFFECT_WING_COSTUME16,
			EFFECT_WEAPON_COSTUME16_SWORD,
			EFFECT_WEAPON_COSTUME16_DAGGER,
			EFFECT_WEAPON_COSTUME16_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME16_BOW,
			EFFECT_WEAPON_COSTUME16_TWO_HANDED,
			EFFECT_WEAPON_COSTUME16_BELL,
			EFFECT_WEAPON_COSTUME16_FAN,
			EFFECT_WEAPON_COSTUME16_FAN_LEFT,
			EFFECT_BODY_COSTUME17 = 823,
			EFFECT_WEAPON_COSTUME17_SWORD,
			EFFECT_WEAPON_COSTUME17_TWO_HANDED,
			EFFECT_WEAPON_COSTUME17_DAGGER,
			EFFECT_WEAPON_COSTUME17_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME17_BOW,
			EFFECT_WEAPON_COSTUME17_BELL,
			EFFECT_WEAPON_COSTUME17_FAN,
			EFFECT_WEAPON_COSTUME17_FAN_LEFT,
			EFFECT_BODY_COSTUME18 = 832,
			EFFECT_WEAPON_COSTUME18_SWORD,
			EFFECT_WEAPON_COSTUME18_TWO_HANDED,
			EFFECT_WEAPON_COSTUME18_DAGGER,
			EFFECT_WEAPON_COSTUME18_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME18_BOW,
			EFFECT_WEAPON_COSTUME18_BELL,
			EFFECT_WEAPON_COSTUME18_FAN,
			EFFECT_WEAPON_COSTUME18_FAN_LEFT,
			EFFECT_BODY_COSTUME19 = 841,
			EFFECT_WEAPON_COSTUME19_SWORD,
			EFFECT_WEAPON_COSTUME19_TWO_HANDED,
			EFFECT_WEAPON_COSTUME19_DAGGER,
			EFFECT_WEAPON_COSTUME19_DAGGER_LEFT,
			EFFECT_WEAPON_COSTUME19_BOW,
			EFFECT_WEAPON_COSTUME19_BELL,
			EFFECT_WEAPON_COSTUME19_FAN,
			EFFECT_WEAPON_COSTUME19_FAN_LEFT, /// itt a vége
			EFFECT_REFINED_NUM = EFFECT_WEAPON_COSTUME19_FAN_LEFT + 100,
		};

		enum DamageFlag
		{
			DAMAGE_NORMAL	= (1<<0),
			DAMAGE_POISON	= (1<<1),
			DAMAGE_DODGE	= (1<<2),
			DAMAGE_BLOCK	= (1<<3),
			DAMAGE_PENETRATE= (1<<4),
			DAMAGE_CRITICAL = (1<<5),
			// ¹Ý-_-»ç
		};

		enum
		{
			EFFECT_DUST,
			EFFECT_STUN,
			EFFECT_HIT,
			EFFECT_FLAME_ATTACK,
			EFFECT_FLAME_HIT,
			EFFECT_FLAME_ATTACH,
			EFFECT_ELECTRIC_ATTACK,
			EFFECT_ELECTRIC_HIT,
			EFFECT_ELECTRIC_ATTACH,
			EFFECT_SPAWN_APPEAR,
			EFFECT_SPAWN_DISAPPEAR,
			EFFECT_LEVELUP,
			EFFECT_SKILLUP,
			EFFECT_HPUP_RED,
			EFFECT_SPUP_BLUE,
			EFFECT_SPEEDUP_GREEN,
			EFFECT_DXUP_PURPLE,
			EFFECT_CRITICAL,
			EFFECT_PENETRATE,
			EFFECT_BLOCK,
			EFFECT_DODGE,
			EFFECT_FIRECRACKER,
			EFFECT_SPIN_TOP,
			EFFECT_WEAPON,
			EFFECT_WEAPON_END = EFFECT_WEAPON + WEAPON_NUM,
			EFFECT_AFFECT,
			EFFECT_AFFECT_GYEONGGONG = EFFECT_AFFECT + AFFECT_GYEONGGONG,
			EFFECT_AFFECT_KWAESOK = EFFECT_AFFECT + AFFECT_KWAESOK,
			EFFECT_AFFECT_END = EFFECT_AFFECT + AFFECT_NUM,
			EFFECT_EMOTICON,
			EFFECT_EMOTICON_END = EFFECT_EMOTICON + EMOTICON_NUM,
			EFFECT_SELECT,
			EFFECT_TARGET,
			EFFECT_EMPIRE,
			EFFECT_EMPIRE_END = EFFECT_EMPIRE + EMPIRE_NUM,
			EFFECT_HORSE_DUST,
			EFFECT_REFINED,
			EFFECT_REFINED_END = EFFECT_REFINED + EFFECT_REFINED_NUM,
			EFFECT_DAMAGE_TARGET,
			EFFECT_DAMAGE_NOT_TARGET,
			EFFECT_DAMAGE_SELFDAMAGE,
			EFFECT_DAMAGE_SELFDAMAGE2,
			EFFECT_DAMAGE_POISON,
			EFFECT_DAMAGE_MISS,
			EFFECT_DAMAGE_TARGETMISS,
			EFFECT_DAMAGE_CRITICAL,
			EFFECT_SUCCESS,
			EFFECT_FAIL,
			EFFECT_FR_SUCCESS,
			EFFECT_LEVELUP_ON_14_FOR_GERMANY,	//·¹º§¾÷ 14ÀÏ¶§ ( µ¶ÀÏÀü¿ë )
			EFFECT_LEVELUP_UNDER_15_FOR_GERMANY,//·¹º§¾÷ 15ÀÏ¶§ ( µ¶ÀÏÀü¿ë )
			EFFECT_PERCENT_DAMAGE1,
			EFFECT_PERCENT_DAMAGE2,
			EFFECT_PERCENT_DAMAGE3,
			EFFECT_AUTO_HPUP,
			EFFECT_AUTO_SPUP,
			EFFECT_RAMADAN_RING_EQUIP,			// ÃÊ½Â´Þ ¹ÝÁö Âø¿ë ¼ø°£¿¡ ¹ßµ¿ÇÏ´Â ÀÌÆåÆ®
			EFFECT_HALLOWEEN_CANDY_EQUIP,		// ÇÒ·ÎÀ© »çÅÁ Âø¿ë ¼ø°£¿¡ ¹ßµ¿ÇÏ´Â ÀÌÆåÆ®
			EFFECT_HAPPINESS_RING_EQUIP,				// Çàº¹ÀÇ ¹ÝÁö Âø¿ë ¼ø°£¿¡ ¹ßµ¿ÇÏ´Â ÀÌÆåÆ®
			EFFECT_LOVE_PENDANT_EQUIP,				// Çàº¹ÀÇ ¹ÝÁö Âø¿ë ¼ø°£¿¡ ¹ßµ¿ÇÏ´Â ÀÌÆåÆ®
			#ifdef VERSION_162_ENABLED
			EFFECT_HEALER,
#endif
			EFFECT_TEMP,
			EFFECT_BOSS,
			EFFECT_UNUSED1,
#ifdef ENABLE_ACCE_SYSTEM
			EFFECT_ACCE_SUCCEDED,
			EFFECT_ACCE_EQUIP,
#endif
#ifdef ENABLE_TALISMAN_EFFECT
			EFFECT_TALISMAN_EQUIP_FIRE,
			EFFECT_TALISMAN_EQUIP_ICE,
			EFFECT_TALISMAN_EQUIP_WIND,
			EFFECT_TALISMAN_EQUIP_EARTH,
			EFFECT_TALISMAN_EQUIP_DARK,
			EFFECT_TALISMAN_EQUIP_ELEC,
#endif
#ifdef ENABLE_RUNE_SYSTEM
			EFFECT_RUNE,
#endif
#ifdef __EFFETTO_MANTELLO__
			EFFECT_MANTELLO,
#endif
#ifdef ENABLE_NEW_GYEONGGONG_SKILL
			EFFECT_GYEONGGONG_BOOM,
#endif
			EFFECT_NUM,
		};

		enum
		{
			DUEL_NONE,
			DUEL_CANNOTATTACK,
			DUEL_START,
		};

	public:
		static void DestroySystem();
		static void CreateSystem(UINT uCapacity);
#ifdef ENABLE_SKILL_COLOR_SYSTEM
		static bool RegisterEffect(UINT eEftType, const char* c_szEftAttachBone, const char* c_szEftName, bool isCache, const char* name = nullptr);
#else
		static bool RegisterEffect(UINT eEftType, const char* c_szEftAttachBone, const char* c_szEftName, bool isCache);
#endif
#ifdef ENABLE_GENDER_ALIGNMENT
		static void RegisterTitleName(const int iIndex, const char * c_szTitleNameF, const char * c_szTitleNameM);
#else
		static void RegisterTitleName(int iIndex, const char * c_szTitleName);
#endif
		static bool RegisterNameColor(UINT uIndex, UINT r, UINT g, UINT b);
		static bool RegisterTitleColor(UINT uIndex, UINT r, UINT g, UINT b);
		//static bool ChangeEffectTexture(UINT eEftType, const char* c_szSrcFileName, const char* c_szDstFileName);

		static void SetDustGap(float fDustGap);
		static void SetHorseDustGap(float fDustGap);

		static void SetEmpireNameMode(bool isEnable);
		static const D3DXCOLOR& GetIndexedNameColor(UINT eNameColor);
#ifdef MEMORY_LEAK_FIX_RAZRO93
private:
	CCylinderCollisionInstance* m_pCylinderCollisionInstance;
#endif
	public:
		void SetMainInstance();

		void OnSelected();
		void OnUnselected();
		void OnTargeted();
		void OnUntargeted();
#ifdef __AUTO_QUQUE_ATTACK__
		void SetAutoFarmAffect(const bool bStatus);
#endif

	protected:
		bool __IsExistMainInstance();
		bool __IsMainInstance();
		bool __MainCanSeeHiddenThing();
		float __GetBowRange();

	protected:
		uint32_t	__AttachEffect(UINT eEftType);
		uint32_t	__AttachEffect(char filename[128]);
		void	__DetachEffect(uint32_t dwEID);

	public:
		void CreateSpecialEffect(uint32_t iEffectIndex);
		void AttachSpecialEffect(uint32_t effect);

	protected:
		static std::string ms_astAffectEffectAttachBone[EFFECT_NUM];
		static uint32_t ms_adwCRCAffectEffect[EFFECT_NUM];
		static float ms_fDustGap;
		static float ms_fHorseDustGap;

	public:
		CInstanceBase();
		virtual ~CInstanceBase();

		bool LessRenderOrder(CInstanceBase* pkInst);

		void MountHorse(UINT eRace);
		void DismountHorse();
#ifdef ENABLE_MOUNT_COUNT_ABOVE_CHAR_RAZOR93
		void SetMountCountOverhead(const char* szText);
#endif // ENABLE_MOUNT_COUNT_ABOVE_CHAR_RAZOR93

		

		// ½ºÅ©¸³Æ®¿ë Å×½ºÆ® ÇÔ¼ö. ³ªÁß¿¡ ¾ø¿¡ÀÚ
		void SCRIPT_SetAffect(UINT eAffect, bool isVisible);

		float CalculateDistanceSq3d(const TPixelPosition& c_rkPPosDst);

		// Instance Data
		bool IsFlyTargetObject();
		void ClearFlyTargetInstance();
		void SetFlyTargetInstance(CInstanceBase& rkInstDst);
		void AddFlyTargetInstance(CInstanceBase& rkInstDst);
		void AddFlyTargetPosition(const TPixelPosition& c_rkPPosDst);

		float GetFlyTargetDistance();

		void SetAlpha(float fAlpha);

		void DeleteBlendOut();

		void					AttachTextTail();
		void					DetachTextTail();
		void					UpdateTextTailLevel(uint32_t level);

		void					RefreshTextTail();
		void					RefreshTextTailTitle();

		bool					Create(const SCreateData& c_rkCreateData, bool wikiPreview = false);

		bool					CreateDeviceObjects();
		void					DestroyDeviceObjects();

		void					Destroy();

		void					Update();
		bool					UpdateDeleting();

		void					Transform();
		void					Deform();
		void					Render();
		void					RenderTrace();
		void					RenderToShadowMap();
		void					RenderCollision();
		void					RegisterBoundingSphere();

		// Temporary
		void					GetBoundBox(D3DXVECTOR3 * vtMin, D3DXVECTOR3 * vtMax);

		void					SetNameString(const char* c_szName, int len);
		bool					SetRace(uint32_t dwRaceIndex);
		void					SetVirtualID(uint32_t wVirtualNumber);
		void					SetVirtualNumber(uint32_t dwVirtualNumber);
		void					SetInstanceType(int iInstanceType);
		void					SetAlignment(uint32_t sAlignment);
#ifdef NEW_PET_SYSTEM
		void					SetLevelText(int mLevel);
#endif
		void					SetPKMode(uint8_t byPKMode);
		void					SetKiller(bool bFlag);
		void					SetPartyMemberFlag(bool bFlag);
		void					SetStateFlags(uint32_t dwStateFlags);
		void					SetArmor(uint32_t dwArmor);
		void					SetShape(uint32_t eShape, float fSpecular=0.0f);
		void					SetHair(uint32_t eHair);
#ifdef ENABLE_ACCE_SYSTEM
		void					SetAcce(uint32_t dwAcce, bool wikiPreview = false);
		void					ChangeAcce(uint32_t dwAcce);
#endif
#ifdef ENABLE_COSTUME_EFFECT
		void	ClearCostumeEffect(bool bIsBody);
		void	ChangeCostumeEffect(bool bIsBody, uint32_t dwEffectID, bool effect = false);
#endif
		bool					SetWeapon(uint32_t eWeapon);
		bool					ChangeArmor(uint32_t dwArmor);
		void					ChangeWeapon(uint32_t eWeapon);
		void					ChangeHair(uint32_t eHair);
		void					ChangeGuild(uint32_t dwGuildID);
#ifdef ENABLE_SKILL_COLOR_SYSTEM
		void					ChangeSkillColor(const uint32_t * dwSkillColor);
#endif

		uint32_t					GetWeaponType();

#ifdef ENABLE_MULTI_LANGUAGE
		void					SetLanguage(uint8_t bLang) { m_bLanguage = bLang; }
		uint8_t					GetLanguage() const { return m_bLanguage; }
#endif

		void					SetComboType(UINT uComboType);
		void					SetAttackSpeed(UINT uAtkSpd);
		void					SetMoveSpeed(UINT uMovSpd);
		void					SetRotationSpeed(float fRotSpd);

		const char *			GetNameString();
#if defined (ENABLE_LEVEL_IN_TRADE) && defined(ENABLE_NEW_EXCHANGE_WINDOW)
		uint32_t					GetLevel();
#endif
#ifdef ENABLE_TEXT_LEVEL_REFRESH
		void					SetLevel(uint32_t dwLevel);
#endif
		int						GetInstanceType();
		uint32_t					GetPart(CRaceData::EParts part);
		uint32_t					GetShape();
		uint32_t					GetRace();
		uint32_t					GetRank();
		uint32_t					GetVirtualID();
		uint32_t					GetVirtualNumber();
		uint32_t					GetEmpireID();
		uint32_t					GetGuildID();

#ifdef ENABLE_SKILL_COLOR_SYSTEM
		uint32_t *					GetSkillColor(const uint32_t dwSkillIndex);
#endif

		uint32_t						GetAlignment();
		uint32_t					GetAlignmentGrade();
		//int						GetAlignmentType();
		uint8_t					GetPKMode();
		bool					IsKiller();
		bool					IsPartyMember();

		void					ActDualEmotion(CInstanceBase & rkDstInst, WORD dwMotionNumber1, WORD dwMotionNumber2);
		void					ActEmotion(uint32_t dwMotionNumber);
		void					LevelUp();
		void					SkillUp();
		void					UseSpinTop();
		void					Revive();
		void					Stun();
		void					Die();
		void					Hide();
		void					Show();

		bool					CanAct();
		bool					CanMove();
		bool					CanAttack();
		bool					CanUseSkill();
		bool					CanFishing();
		//bool					IsConflictAlignmentInstance(CInstanceBase& rkInstVictim);
		bool					IsAttackableInstance(CInstanceBase& rkInstVictim);
		bool					IsTargetableInstance(CInstanceBase& rkInstVictim);
		bool					IsPVPInstance(CInstanceBase& rkInstVictim);
		bool					CanChangeTarget();
		bool					CanPickInstance();
		bool					CanViewTargetHP(CInstanceBase& rkInstVictim);


		// Movement
		bool					IsGoing();
		bool					NEW_Goto(const TPixelPosition& c_rkPPosDst, float fDstRot);
		void					EndGoing();

		void					SetRunMode();
		void					SetWalkMode();

		bool					IsAffect(UINT uAffect);
		bool					IsInvisibility();
		bool					IsParalysis();
		bool					IsGameMaster();
		bool					IsSA();
		bool					IsSameEmpire(CInstanceBase& rkInstDst);
		bool					IsBowMode();
		bool					IsHandMode();
		bool					IsFishingMode();
		bool					IsFishing();

		bool					IsWearingDress();
		bool					IsHoldingPickAxe();
		bool					IsMountingHorse();
		bool					IsNewMount();
		bool					IsForceVisible();
		bool					IsInSafe();
#ifdef NEW_PET_SYSTEM
		bool					IsNewPet();
#endif		
		bool					IsEnemy();
		bool					IsStone();
		bool					IsResource();
		bool					IsNPC();
		bool					IsPC();
		bool					IsPoly();
		bool					IsWarp();
		bool					IsGoto();
		bool					IsObject();
		bool					IsDoor();
		bool					IsBuilding();
		bool					IsWoodenDoor();
		bool					IsStoneDoor();
		bool					IsFlag();
		bool					IsGuildWall();

		bool					IsDead();
		bool					IsStun();
		bool					IsSleep();
		bool					__IsSyncing();
		bool					IsWaiting();
		bool					IsWalking();
		bool					IsPushing();
		bool					IsAttacking();
		bool					IsActingEmotion();
		bool					IsAttacked();
		bool					IsKnockDown();
		bool					IsUsingSkill();
		bool					IsUsingMovingSkill();
		bool					CanCancelSkill();
		bool					CanAttackHorseLevel();

#ifdef __MOVIE_MODE__
		bool					IsMovieMode(); // ¿î¿µÀÚ¿ë ¿ÏÀüÈ÷ ¾Èº¸ÀÌ´Â°Å
#endif
		bool					NEW_CanMoveToDestPixelPosition(const TPixelPosition& c_rkPPosDst);

		void					NEW_SetAdvancingRotationFromPixelPosition(const TPixelPosition& c_rkPPosSrc, const TPixelPosition& c_rkPPosDst);
		void					NEW_SetAdvancingRotationFromDirPixelPosition(const TPixelPosition& c_rkPPosDir);
		bool					NEW_SetAdvancingRotationFromDestPixelPosition(const TPixelPosition& c_rkPPosDst);
		void					SetAdvancingRotation(float fRotation);

		void					EndWalking(float fBlendingTime=0.15f);
		void					EndWalkingWithoutBlending();

		// Battle
		void					SetEventHandler(CActorInstance::IEventHandler* pkEventHandler);

		void					PushUDPState(uint32_t dwCmdTime, const TPixelPosition& c_rkPPosDst, float fDstRot, UINT eFunc, UINT uArg);
		void					PushTCPState(uint32_t dwCmdTime, const TPixelPosition& c_rkPPosDst, float fDstRot, UINT eFunc, UINT uArg);
		void					PushTCPStateExpanded(uint32_t dwCmdTime, const TPixelPosition& c_rkPPosDst, float fDstRot, UINT eFunc, UINT uArg, UINT uTargetVID);

		void					NEW_Stop();

		bool					NEW_UseSkill(UINT uSkill, UINT uMot, UINT uMotLoopCount, bool isMovingSkill);
		void					NEW_Attack();
		void					NEW_Attack(float fDirRot);
		void					NEW_AttackToDestPixelPositionDirection(const TPixelPosition& c_rkPPosDst);
		bool					NEW_AttackToDestInstanceDirection(CInstanceBase& rkInstDst, IFlyEventHandler* pkFlyHandler);
		bool					NEW_AttackToDestInstanceDirection(CInstanceBase& rkInstDst);

		bool					NEW_MoveToDestPixelPositionDirection(const TPixelPosition& c_rkPPosDst);
		void					NEW_MoveToDestInstanceDirection(CInstanceBase& rkInstDst);
		void					NEW_MoveToDirection(float fDirRot);

		float					NEW_GetDistanceFromDirPixelPosition(const TPixelPosition& c_rkPPosDir);
		float					NEW_GetDistanceFromDestPixelPosition(const TPixelPosition& c_rkPPosDst);
		float					NEW_GetDistanceFromDestInstance(CInstanceBase& rkInstDst);

		float					NEW_GetRotation();
		float					NEW_GetRotationFromDestPixelPosition(const TPixelPosition& c_rkPPosDst);
		float					NEW_GetRotationFromDirPixelPosition(const TPixelPosition& c_rkPPosDir);
		float					NEW_GetRotationFromDestInstance(CInstanceBase& rkInstDst);

		float					NEW_GetAdvancingRotationFromDirPixelPosition(const TPixelPosition& c_rkPPosDir);
		float					NEW_GetAdvancingRotationFromDestPixelPosition(const TPixelPosition& c_rkPPosDst);
		float					NEW_GetAdvancingRotationFromPixelPosition(const TPixelPosition& c_rkPPosSrc, const TPixelPosition& c_rkPPosDst);

		bool					NEW_IsClickableDistanceDestPixelPosition(const TPixelPosition& c_rkPPosDst);
		bool					NEW_IsClickableDistanceDestInstance(CInstanceBase& rkInstDst);

		bool					NEW_GetFrontInstance(CInstanceBase ** ppoutTargetInstance, float fDistance);
		void					NEW_GetRandomPositionInFanRange(CInstanceBase& rkInstTarget, TPixelPosition* pkPPosDst);
		bool					NEW_GetInstanceVectorInFanRange(float fSkillDistance, CInstanceBase& rkInstTarget, std::vector<CInstanceBase*>* pkVct_pkInst);
		bool					NEW_GetInstanceVectorInCircleRange(float fSkillDistance, std::vector<CInstanceBase*>* pkVct_pkInst);

		void					NEW_SetOwner(uint32_t dwOwnerVID);
		void					NEW_SyncPixelPosition(int32_t& nPPosX, int32_t& nPPosY);
		void					NEW_SyncCurrentPixelPosition();

		void					NEW_SetPixelPosition(const TPixelPosition& c_rkPPosDst);

		bool					NEW_IsLastPixelPosition();
		const TPixelPosition&	NEW_GetLastPixelPositionRef();


		// Battle
		bool					isNormalAttacking();
		bool					isComboAttacking();
		MOTION_KEY				GetNormalAttackIndex();
		uint32_t					GetComboIndex();
		float					GetAttackingElapsedTime();
		void					InputNormalAttack(float fAtkDirRot);
		void					InputComboAttack(float fAtkDirRot);

		void					RunNormalAttack(float fAtkDirRot);
		void					RunComboAttack(float fAtkDirRot, uint32_t wMotionIndex);

		CInstanceBase*			FindNearestVictim();
		bool					CheckAdvancing();


		bool					AvoidObject(const CGraphicObjectInstance& c_rkBGObj);
		bool					IsBlockObject(const CGraphicObjectInstance& c_rkBGObj);
		void					BlockMovement();

	public:
		bool					CheckAttacking(CInstanceBase& rkInstVictim);
		void					ProcessHitting(uint32_t dwMotionKey, CInstanceBase * pVictimInstance);
		void					ProcessHitting(uint32_t dwMotionKey, uint8_t byEventIndex, CInstanceBase * pVictimInstance);
		void					GetBlendingPosition(TPixelPosition * pPixelPosition);
		void					SetBlendingPosition(const TPixelPosition & c_rPixelPosition);

		// Fishing
		void					StartFishing(float frot);
		void					StopFishing();
		void					ReactFishing();
		void					CatchSuccess();
		void					CatchFail();
		bool					GetFishingRot(int * pirot);

		// Render Mode
		void					RestoreRenderMode();
		void					SetAddRenderMode();
		void					SetModulateRenderMode();
		void					SetRenderMode(int iRenderMode);
		void					SetAddColor(const D3DXCOLOR & c_rColor);

		// Position
		void					SCRIPT_SetPixelPosition(float fx, float fy);
		void					NEW_GetPixelPosition(TPixelPosition * pPixelPosition);

		// Rotation
		void					NEW_LookAtFlyTarget();
		void					NEW_LookAtDestInstance(CInstanceBase& rkInstDst);
		void					NEW_LookAtDestPixelPosition(const TPixelPosition& c_rkPPosDst);

		float					GetRotation();
		float					GetAdvancingRotation();
		void					SetRotation(float fRotation);
		void					BlendRotation(float fRotation, float fBlendTime = 0.1f);

		void					SetDirection(int dir);
		void					BlendDirection(int dir, float blendTime);
		float					GetDegreeFromDirection(int dir);

		// Motion
		//	Motion Deque
		bool					isLock();

		void					SetMotionMode(int iMotionMode);
		int						GetMotionMode(uint32_t dwMotionIndex);

		// Motion
		//	Pushing Motion
		void					ResetLocalTime();
		void					SetLoopMotion(WORD wMotion, float fBlendTime=0.1f, float fSpeedRatio=1.0f);
		void					PushOnceMotion(WORD wMotion, float fBlendTime=0.1f, float fSpeedRatio=1.0f);
		void					PushLoopMotion(WORD wMotion, float fBlendTime=0.1f, float fSpeedRatio=1.0f);
		void					SetEndStopMotion();

		// Intersect
		bool					IntersectDefendingSphere();
		bool					IntersectBoundingBox();

		// Part
		//void					SetParts(const WORD * c_pParts);
		void					Refresh(uint32_t dwMotIndex, bool isLoop);

		//void					AttachEffectByID(uint32_t dwParentPartIndex, const char * c_pszBoneName, uint32_t dwEffectID, int dwLife = CActorInstance::EFFECT_LIFE_INFINITE ); // ¼ö¸íÀº ms´ÜÀ§ÀÔ´Ï´Ù.
		//void					AttachEffectByName(uint32_t dwParentPartIndex, const char * c_pszBoneName, const char * c_pszEffectName, int dwLife = CActorInstance::EFFECT_LIFE_INFINITE ); // ¼ö¸íÀº ms´ÜÀ§ÀÔ´Ï´Ù.

		float					GetDistance(CInstanceBase * pkTargetInst);
		float					GetDistance(const TPixelPosition & c_rPixelPosition);
#ifdef ENABLE_RACE_HEIGHT
		float					GetBaseHeight();
#endif
		// ETC
		CActorInstance&			GetGraphicThingInstanceRef();
		CActorInstance*			GetGraphicThingInstancePtr();

		bool __Background_IsWaterPixelPosition(const TPixelPosition& c_rkPPos);
		bool __Background_GetWaterHeight(const TPixelPosition& c_rkPPos, float* pfHeight);

		// 2004.07.25.myevan.ÀÌÆåÆ® ¾È³ª¿À´Â ¹®Á¦
		/////////////////////////////////////////////////////////////
		void __ClearAffectFlagContainer();
		void __ClearAffects();
		/////////////////////////////////////////////////////////////

		void __SetAffect(UINT eAffect, bool isVisible);

		void SetAffectFlagContainer(const CAffectFlagContainer& c_rkAffectFlagContainer);

		void __SetNormalAffectFlagContainer(const CAffectFlagContainer& c_rkAffectFlagContainer);
		void __SetStoneSmokeFlagContainer(const CAffectFlagContainer& c_rkAffectFlagContainer);

		void SetEmoticon(UINT eEmoticon);
		void SetFishEmoticon();
		bool IsPossibleEmoticon();

	protected:
		UINT					__LessRenderOrder_GetLODLevel();
		void					__Initialize();
		void					__InitializeRotationSpeed();

		void					__Create_SetName(const SCreateData& c_rkCreateData);
		void					__Create_SetWarpName(const SCreateData& c_rkCreateData);

		CInstanceBase*			__GetMainInstancePtr();
		CInstanceBase*			__FindInstancePtr(uint32_t dwVID);

		bool  __FindRaceType(uint32_t dwRace, uint8_t* pbType);
		uint32_t __GetRaceType();

		bool __IsShapeAnimalWear();
		bool __IsChangableWeapon(uint32_t iWeaponID);

		void __EnableSkipCollision();
		void __DisableSkipCollision();

		void __ClearMainInstance();

		void __Shaman_SetParalysis(bool isParalysis);
		void __Warrior_SetGeomgyeongAffect(bool isVisible);
#ifdef ENABLE_NEW_GYEONGGONG_SKILL
		void __Assassin_SetGyeongGongAffect(bool isVisible);
#endif
		void __Assassin_SetEunhyeongAffect(bool isVisible);
		void __SetReviveInvisibilityAffect(bool isVisible);

		bool __CanProcessNetworkStatePacket();

		bool __IsInDustRange();

		// Emotion
		void __ProcessFunctionEmotion(uint32_t dwMotionNumber, uint32_t dwTargetVID, const TPixelPosition & c_rkPosDst);
		void __EnableChangingTCPState();
		void __DisableChangingTCPState();
		bool __IsEnableTCPProcess(UINT eCurFunc);

		// 2004.07.17.levites.isShow¸¦ ViewFrustumCheck·Î º¯°æ
		bool __CanRender();
		bool __IsInViewFrustum();

		// HORSE
		void __AttachHorseSaddle();
		void __DetachHorseSaddle();

		struct SHORSE
		{
			bool m_isMounting;
			CActorInstance* m_pkActor;

			SHORSE();
			~SHORSE();

			void Destroy();
			void Create(const TPixelPosition& c_rkPPos, UINT eRace, UINT eHitEffect);

			void SetAttackSpeed(UINT uAtkSpd);
			void SetMoveSpeed(UINT uMovSpd);
			void Deform();
			void Render();
			CActorInstance& GetActorRef();
			CActorInstance* GetActorPtr();

			bool IsMounting();
			bool CanAttack();
			bool CanUseSkill();

			UINT GetLevel();
			bool IsNewMount();

			void __Initialize();
		} m_kHorse;


	protected:
		// Blend Mode
		void					__SetBlendRenderingMode();
		void					__SetAlphaValue(float fAlpha);
		float					__GetAlphaValue();

		void					__ComboProcess();
		void					MovementProcess();
		void					TodoProcess();
		void					StateProcess();
		void					AttackProcess();

		void					StartWalking();
		float					GetLocalTime();

		void					RefreshState(uint32_t dwMotIndex, bool isLoop);
		void					RefreshActorInstance();

	protected:
		void					OnSyncing();
		void					OnWaiting();
		void					OnMoving();

		void					NEW_SetCurPixelPosition(const TPixelPosition& c_rkPPosDst);
		void					NEW_SetSrcPixelPosition(const TPixelPosition& c_rkPPosDst);
		void					NEW_SetDstPixelPosition(const TPixelPosition& c_rkPPosDst);
		void					NEW_SetDstPixelPositionZ(FLOAT z);

		const TPixelPosition&	NEW_GetCurPixelPositionRef();
		const TPixelPosition&	NEW_GetSrcPixelPositionRef();

	public:
		const TPixelPosition&	NEW_GetDstPixelPositionRef();

	protected:
		bool m_isTextTail;

		// Instance Data
		std::string				m_stName;
		uint32_t					m_awPart[CRaceData::PART_MAX_NUM];

		uint32_t					m_dwLevel;
		uint32_t					m_dwEmpireID;
		uint32_t					m_dwGuildID;

#ifdef ENABLE_SKILL_COLOR_SYSTEM
		uint32_t *					m_dwSkillColor[ESkillColorLength::MAX_SKILL_COUNT + MAX_BUFF_COUNT][ESkillColorLength::MAX_EFFECT_COUNT];
#endif

#ifdef ENABLE_MULTI_LANGUAGE
		uint8_t					m_bLanguage;
#endif

	protected:
		CAffectFlagContainer	m_kAffectFlagContainer;
		uint32_t					m_adwCRCAffectEffect[AFFECT_NUM];

		UINT	__GetRefinedEffect(CItemData* pItem);
#ifdef ENABLE_SHINING_SYSTEM
		void	__GetShiningEffect(CItemData* pItem);
		void	__ClearWeaponShiningEffect(bool detaching = true);
		void	__ClearArmorShiningEffect(bool detaching = true);
		void	__AttachWeaponShiningEffect(int effectIndex, const char* effectFileName, const char* boneName = "Bip01");
		void	__AttachArmorShiningEffect(int effectIndex, const char* effectFileName, const char* boneName = "Bip01");
#endif
		void	__ClearWeaponRefineEffect();
		void	__ClearWeaponRefineEffectCostume();
		void	__ClearArmorRefineEffect();
#ifdef ENABLE_ACCE_SYSTEM
		void	ClearAcceEffect();
#endif

	protected:
		void __AttachSelectEffect();
		void __DetachSelectEffect();

		void __AttachTargetEffect();
		void __DetachTargetEffect();

		void __AttachEmpireEffect(uint32_t eEmpire);

	protected:
		struct SEffectContainer
		{
			typedef std::map<uint32_t, uint32_t> Dict;
			Dict m_kDct_dwEftID;
		} m_kEffectContainer;

		void __EffectContainer_Initialize();
		void __EffectContainer_Destroy();

		uint32_t __EffectContainer_AttachEffect(uint32_t eEffect);
		void __EffectContainer_DetachEffect(uint32_t eEffect);
#ifdef ENABLE_NO_COLLISION
		bool __EffectContainer_IsEffect(uint32_t eEffect);
#endif
		SEffectContainer::Dict& __EffectContainer_GetDict();

	protected:
		struct SStoneSmoke
		{
			uint32_t m_dwEftID;
		} m_kStoneSmoke;

		void __StoneSmoke_Inialize();
		void __StoneSmoke_Destroy();
		void __StoneSmoke_Create(uint32_t eSmoke);


	protected:
		// Emoticon
		//uint32_t					m_adwCRCEmoticonEffect[EMOTICON_NUM];

		uint8_t					m_eType;
		uint8_t					m_eRaceType;
		uint32_t					m_eShape;
		uint32_t					m_dwRace;
		uint32_t					m_dwVirtualNumber;
		uint32_t					m_sAlignment;
		uint8_t					m_byPKMode;
		bool					m_isKiller;
		bool					m_isPartyMember;

		// Movement
		int						m_iRotatingDirection;

		uint32_t					m_dwAdvActorVID;
		uint32_t					m_dwLastDmgActorVID;

		int32_t					m_nAverageNetworkGap;
		uint32_t					m_dwNextUpdateHeightTime;

		bool					m_isGoing;

		TPixelPosition			m_kPPosDust;

		uint32_t					m_dwLastComboIndex;

		uint32_t					m_swordRefineEffectRight;
		uint32_t					m_swordRefineEffectLeft;
		uint32_t					m_armorRefineEffect;
#ifdef ENABLE_SHINING_SYSTEM
		//2-Dimensions for Left & Right sided effects
		uint32_t					m_weaponShiningEffects[2][CItemData::ITEM_SHINING_MAX_COUNT];
		uint32_t					m_armorShiningEffects[CItemData::ITEM_SHINING_MAX_COUNT];
#endif
#ifdef ENABLE_ACCE_SYSTEM
		uint32_t					m_dwAcceEffect;
#endif
#ifdef ENABLE_COSTUME_EFFECT
		uint32_t	m_dwCostumeBodyEffect;
		uint32_t	m_dwCostumeWeaponRightEffect;
		uint32_t	m_dwCostumeWeaponLeftEffect;
#endif
		struct SMoveAfterFunc
		{
			UINT eFunc = 0;
			UINT uArg = 0;

			// For Emotion Function
			UINT uArgExpanded = 0;
			TPixelPosition kPosDst = { 0, 0, 0 };
		};

		SMoveAfterFunc m_kMovAfterFunc;

		float m_fDstRot;
		float m_fAtkPosTime;
		float m_fRotSpd;
		float m_fMaxRotSpd;

		bool m_bEnableTCPState;

		// Graphic Instance
		CActorInstance m_GraphicThingInstance;


	protected:
		struct SCommand
		{
			uint32_t	m_dwChkTime;
			uint32_t	m_dwCmdTime;
			float	m_fDstRot;
			UINT 	m_eFunc;
			UINT 	m_uArg;
			UINT	m_uTargetVID;
			TPixelPosition m_kPPosDst;

			SCommand() : m_dwChkTime(0), m_dwCmdTime(0), m_fDstRot(0.0f), m_eFunc(0), m_uArg(0), m_uTargetVID(0) {}
		};

		typedef std::list<SCommand> CommandQueue;

		uint32_t		m_dwBaseChkTime;
		uint32_t		m_dwBaseCmdTime;

		uint32_t		m_dwSkipTime;

		CommandQueue m_kQue_kCmdNew;

		bool		m_bDamageEffectType;

		struct SEffectDamage
		{
			uint32_t damage;
			uint8_t flag;
			bool bSelf;
			bool bTarget;
		};

		typedef std::list<SEffectDamage> CommandDamageQueue;
		CommandDamageQueue m_DamageQueue;

		bool ProcessDamage();

	public:
		void AddDamageEffect(uint32_t damage, uint8_t flag, bool bSelf, bool bTarget);
		bool __ProcessSingleDamage(const SEffectDamage& sDamage);

	protected:
		struct SWarrior
		{
			uint32_t m_dwGeomgyeongEffect;
		};

		SWarrior m_kWarrior;

		void __Warrior_Initialize();

#ifdef ENABLE_NEW_GYEONGGONG_SKILL
	protected:
		struct SAssassin
		{
			uint32_t m_dwGyeongGongEffect;
		};

		SAssassin m_kAssassin;

		void __Assassin_Initialize();
#endif

	public:
		static void ClearPVPKeySystem();

		static void InsertPVPKey(uint32_t dwSrcVID, uint32_t dwDstVID);
		static void InsertPVPReadyKey(uint32_t dwSrcVID, uint32_t dwDstVID);
		static void RemovePVPKey(uint32_t dwSrcVID, uint32_t dwDstVID);

		static void InsertGVGKey(uint32_t dwSrcGuildVID, uint32_t dwDstGuildVID);
		static void RemoveGVGKey(uint32_t dwSrcGuildVID, uint32_t dwDstGuildVID);

		static void InsertDUELKey(uint32_t dwSrcVID, uint32_t dwDstVID);

		UINT GetNameColorIndex();

		const D3DXCOLOR& GetNameColor();
		const D3DXCOLOR& GetTitleColor();

	protected:
		static uint32_t __GetPVPKey(uint32_t dwSrcVID, uint32_t dwDstVID);
		static bool __FindPVPKey(uint32_t dwSrcVID, uint32_t dwDstVID);
		static bool __FindPVPReadyKey(uint32_t dwSrcVID, uint32_t dwDstVID);
		static bool __FindGVGKey(uint32_t dwSrcGuildID, uint32_t dwDstGuildID);
		static bool __FindDUELKey(uint32_t dwSrcGuildID, uint32_t dwDstGuildID);

	protected:
		CActorInstance::IEventHandler* GetEventHandlerPtr();
		CActorInstance::IEventHandler& GetEventHandlerRef();

	protected:
		static float __GetBackgroundHeight(float x, float y);
		static uint32_t __GetShadowMapColor(float x, float y);

	public:
		static void ResetPerformanceCounter();
		static void GetInfo(std::string* pstInfo);

	public:
		static CInstanceBase* New();
		static void Delete(CInstanceBase* pkInst);

		static CDynamicPool<CInstanceBase>	ms_kPool;

	protected:
		static uint32_t ms_dwUpdateCounter;
		static uint32_t ms_dwRenderCounter;
		static uint32_t ms_dwDeformCounter;

	public:
		uint32_t					GetDuelMode();
		void					SetDuelMode(uint32_t type);
	protected:
		uint32_t					m_dwDuelMode;
		uint32_t					m_dwEmoticonTime;

	protected:
		bool m_IsAlwaysRender;
	public:
		bool IsAlwaysRender();
		void SetAlwaysRender(bool val);
		

#if defined(WJ_SHOW_MOB_INFO) && defined(ENABLE_SHOW_MOBAIFLAG)
	public:
		void					MobInfoAiFlagRefresh();
#endif
#if defined(WJ_SHOW_MOB_INFO) && defined(ENABLE_SHOW_MOBLEVEL)
	public:
		void					MobInfoLevelRefresh();
#endif
#ifdef ENABLE_RUNE_SYSTEM
	public:
		void	SetRune(uint32_t dwRune, bool effect = false);

	protected:
		uint32_t	m_runeEffect;
		
		void	SetRuneEffect(bool effect = false);
		void	ClearRuneEffect();
#endif
};

inline int RaceToJob(int race)
{
	constexpr int JOB_NUM = 4;
	return race % JOB_NUM;
}

inline int RaceToSex(int race)
{
	switch (race)
	{
		case 0:
		case 2:
		case 5:
		case 7:
			return 1;
		case 1:
		case 3:
		case 4:
		case 6:
			return 0;

	}
	return 0;
}