add_subdirectory(AudioLib)
add_subdirectory(Base)
add_subdirectory(Effect)
add_subdirectory(FoxFS)
add_subdirectory(Game)
add_subdirectory(Granny)
add_subdirectory(Image)
add_subdirectory(Pack)
add_subdirectory(Python)
add_subdirectory(Render)
add_subdirectory(Script)
add_subdirectory(SecureLayer)
add_subdirectory(SpeedTree)
add_subdirectory(Sphere)
add_subdirectory(Terrain)
add_subdirectory(UserInterface)


set_target_properties(AudioLib PROPERTIES FOLDER Launcher)
set_target_properties(Base PROPERTIES FOLDER Launcher)
set_target_properties(Effect PROPERTIES FOLDER Launcher)
set_target_properties(FoxFS PROPERTIES FOLDER Launcher)
set_target_properties(Game PROPERTIES FOLDER Launcher)
set_target_properties(Granny PROPERTIES FOLDER Launcher)
set_target_properties(Image PROPERTIES FOLDER Launcher)
set_target_properties(Pack PROPERTIES FOLDER Launcher)
set_target_properties(Python PROPERTIES FOLDER Launcher)
set_target_properties(Render PROPERTIES FOLDER Launcher)
set_target_properties(Script PROPERTIES FOLDER Launcher)
set_target_properties(SecureLayer PROPERTIES FOLDER Launcher)
set_target_properties(SpeedTree PROPERTIES FOLDER Launcher)
set_target_properties(Sphere PROPERTIES FOLDER Launcher)
set_target_properties(Terrain PROPERTIES FOLDER Launcher)
set_target_properties(UserInterface PROPERTIES FOLDER Launcher)
