message("Adding granny2 lib")
add_library(granny2 STATIC IMPORTED GLOBAL)
target_include_directories(granny2
	INTERFACE
	${CMAKE_CURRENT_LIST_DIR}
)
	
set(GRANNY_LIBARY_PATH "")
set(GRANNY_LIBARY_PATH ${CMAKE_CURRENT_LIST_DIR}\\granny2.lib)


set_target_properties(granny2 PROPERTIES
	IMPORTED_LOCATION ${GRANNY_LIBARY_PATH}
	INTERFACE_COMPILE_DEFINITIONS "BUILDING_GRANNY_STATIC=1"
	INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_CURRENT_LIST_DIR}
)