#pragma once
#include "../service.h"
#include "../CommonDefines.h"

enum HEADER_GG
{
	HEADER_GG_LOGIN = 1,
	HEADER_GG_LOGOUT = 2,
	HEADER_GG_RELAY = 3,
	HEADER_GG_NOTICE = 4,
	HEADER_GG_SHUTDOWN = 5,
	HEADER_GG_GUILD = 6,
	HEADER_GG_DISCONNECT = 7,	// 누군가의 접속을 강제로 끊을 때
	HEADER_GG_SHOUT = 8,
	HEADER_GG_SETUP = 9,
	HEADER_GG_MESSENGER_ADD = 10,
	HEADER_GG_MESSENGER_REMOVE = 11,
	HEADER_GG_FIND_POSITION = 12,
	HEADER_GG_WARP_CHARACTER = 13,
	HEADER_GG_MESSENGER_MOBILE = 14,
	HEADER_GG_GUILD_WAR_ZONE_MAP_INDEX = 15,
	HEADER_GG_TRANSFER = 16,
	HEADER_GG_RELOAD_CRC_LIST = 19,
	HEADER_GG_LOGIN_PING = 20,
	HEADER_GG_CHECK_CLIENT_VERSION = 21,
	HEADER_GG_BLOCK_CHAT = 22,

	HEADER_GG_PCBANG_UPDATE = 28,

	HEADER_GG_CHECK_AWAKENESS = 29,
#ifdef ENABLE_FULL_NOTICE
	HEADER_GG_BIG_NOTICE = 30,
#endif
#ifdef ENABLE_SWITCHBOT
	HEADER_GG_SWITCHBOT = 31,
#endif
#ifdef TEXTS_IMPROVEMENT
	HEADER_GG_CHAT_NEW = 32,
#endif
#ifdef ENABLE_WHISPER_ADMIN_SYSTEM	
	HEADER_GG_WHISPER_SYSTEM = 47,
#endif
};

