#pragma once
#include "../service.h"
#include "../CommonDefines.h"

enum HEADER_GC
{

	HEADER_GC_KEY_AGREEMENT_COMPLETED = 0xeb,
	HEADER_GC_KEY_AGREEMENT = 0xec,
	HEADER_GC_TIME_SYNC = 0xed,
	HEADER_GC_PHASE = 0xee,
	HEADER_GC_BINDUDP = 0xef,
	HEADER_GC_HANDSHAKE = 0xf0,

	HEADER_GC_CHARACTER_ADD = 1,
	HEADER_GC_CHARACTER_DEL = 2,
	HEADER_GC_MOVE = 3,
	HEADER_GC_CHAT = 4,
	HEADER_GC_SYNC_POSITION = 5,

	HEADER_GC_LOGIN_SUCCESS = 6,
	HEADER_GC_LOGIN_SUCCESS_NEWSLOT = 32,
	HEADER_GC_LOGIN_FAILURE = 7,

	HEADER_GC_CHARACTER_CREATE_SUCCESS = 8,
	HEADER_GC_CHARACTER_CREATE_FAILURE = 9,
	HEADER_GC_CHARACTER_DELETE_SUCCESS = 10,
	HEADER_GC_CHARACTER_DELETE_WRONG_SOCIAL_ID = 11,

	HEADER_GC_ATTACK = 12,
	HEADER_GC_STUN = 13,
	HEADER_GC_DEAD = 14,

	HEADER_GC_CHARACTER_POINTS = 16,
	HEADER_GC_CHARACTER_POINT_CHANGE = 17,
	HEADER_GC_CHANGE_SPEED = 18,
	HEADER_GC_CHARACTER_UPDATE = 19,
	HEADER_GC_CHARACTER_UPDATE_NEW = 24,

	HEADER_GC_ITEM_DEL = 20,
	HEADER_GC_ITEM_SET = 21,
	HEADER_GC_ITEM_USE = 22,
	HEADER_GC_ITEM_DROP = 23,
	HEADER_GC_ITEM_UPDATE = 25,

	HEADER_GC_ITEM_GROUND_ADD = 26,
	HEADER_GC_ITEM_GROUND_DEL = 27,

	HEADER_GC_QUICKSLOT_ADD = 28,
	HEADER_GC_QUICKSLOT_DEL = 29,
	HEADER_GC_QUICKSLOT_SWAP = 30,

	HEADER_GC_ITEM_OWNERSHIP = 31,

	HEADER_GC_WHISPER = 34,
#ifdef ENABLE_MOUNT_COUNT_ABOVE_CHAR_RAZOR93
	HEADER_GC_BELT_NAME_UPDATE = 245,
	HEADER_GC_MOUNT_COUNT_OVERHEAD = 248,
#endif
#ifdef ENABLE_ITEM_ON_TITLE_RAZOR93
	HEADER_GC_ITEM_ON_TITLE_NAME_UPDATE = 246,
#endif
	HEADER_GC_MOTION = 36,
	HEADER_GC_PARTS = 37,

	HEADER_GC_SHOP = 38,
	HEADER_GC_SHOP_SIGN = 39,
#ifdef ENABLE_FAKE_SHOP_HEADER
	HEADER_GC_FAKE_SHOP_SIGN = 249,
#endif

	HEADER_GC_DUEL_START = 40,
	HEADER_GC_PVP = 41,
	HEADER_GC_EXCHANGE = 42,
	HEADER_GC_CHARACTER_POSITION = 43,

	HEADER_GC_PING = 44,
	HEADER_GC_SCRIPT = 45,
	HEADER_GC_QUEST_CONFIRM = 46,
#ifdef ENABLE_EVENT_MANAGER
	HEADER_GC_EVENT_MANAGER = 147,
#endif

	HEADER_GC_MOUNT = 61,
	HEADER_GC_OWNERSHIP = 62,
	HEADER_GC_TARGET = 63,
#ifdef __SEND_TARGET_INFO__
	HEADER_GC_TARGET_INFO = 58,
#endif
	HEADER_GC_WARP = 65,

	HEADER_GC_ADD_FLY_TARGETING = 69,
	HEADER_GC_CREATE_FLY = 70,
	HEADER_GC_FLY_TARGETING = 71,
	HEADER_GC_SKILL_LEVEL_OLD = 72,
	HEADER_GC_SKILL_LEVEL = 76,

	HEADER_GC_MESSENGER = 74,
	HEADER_GC_GUILD = 75,

	HEADER_GC_PARTY_INVITE = 77,
	HEADER_GC_PARTY_ADD = 78,
	HEADER_GC_PARTY_UPDATE = 79,
	HEADER_GC_PARTY_REMOVE = 80,
	HEADER_GC_QUEST_INFO = 81,
	HEADER_GC_REQUEST_MAKE_GUILD = 82,
	HEADER_GC_PARTY_PARAMETER = 83,

	HEADER_GC_SAFEBOX_SET = 85,
	HEADER_GC_SAFEBOX_DEL = 86,
	HEADER_GC_SAFEBOX_WRONG_PASSWORD = 87,
	HEADER_GC_SAFEBOX_SIZE = 88,

	HEADER_GC_FISHING = 89,

	HEADER_GC_EMPIRE = 90,

	HEADER_GC_PARTY_LINK = 91,
	HEADER_GC_PARTY_UNLINK = 92,
#ifdef ENABLE_ITEMSHOP
	HEADER_GC_ITEMSHOP = 93,
#endif
	HEADER_GC_REFINE_INFORMATION_OLD = 95,
#ifdef LEADERBOARD_RAZOR93

	HEADER_GC_LEADERBOARD_DATA = 250,
	HEADER_GC_LEADERBOARD_NEWS = 251,
	HEADER_GC_LEADERBOARD_GUILD = 252,
#endif
	HEADER_GC_VIEW_EQUIP = 99,

	HEADER_GC_MARK_BLOCK = 100,
	HEADER_GC_MARK_IDXLIST = 102,

	HEADER_GC_TIME = 106,
	HEADER_GC_CHANGE_NAME = 107,

	HEADER_GC_DUNGEON = 110,

	HEADER_GC_WALK_MODE = 111,
	HEADER_GC_SKILL_GROUP = 112,
	HEADER_GC_MAIN_CHARACTER = 113,

	//	HEADER_GC_USE_POTION			= 114,
	HEADER_GC_SEPCIAL_EFFECT = 114,

	HEADER_GC_NPC_POSITION = 115,

	HEADER_GC_LOGIN_KEY = 118,
	HEADER_GC_REFINE_INFORMATION = 119,
	HEADER_GC_CHANNEL = 121,

	// 122 HEADER_GC_MALL_OPEN
	HEADER_GC_TARGET_UPDATE = 123,
	HEADER_GC_TARGET_DELETE = 124,
	HEADER_GC_TARGET_CREATE = 125,

	HEADER_GC_AFFECT_ADD = 126,
	HEADER_GC_AFFECT_REMOVE = 127,

	HEADER_GC_MALL_OPEN = 122,
	HEADER_GC_MALL_SET = 128,
	HEADER_GC_MALL_DEL = 129,

	HEADER_GC_LAND_LIST = 130,
	HEADER_GC_LOVER_INFO = 131,
	HEADER_GC_LOVE_POINT_UPDATE = 132,

	HEADER_GC_SYMBOL_DATA = 133,

	// MINING
	HEADER_GC_DIG_MOTION = 134,
	// END_OF_MINING

	HEADER_GC_DAMAGE_INFO = 135,
	HEADER_GC_CHAR_ADDITIONAL_INFO = 136,

	// SUPPORT_BGM
	HEADER_GC_MAIN_CHARACTER3_BGM = 137,
	HEADER_GC_MAIN_CHARACTER4_BGM_VOL = 138,
	// END_OF_SUPPORT_BGM
#ifdef ENABLE_MULTI_LANGUAGE
		HEADER_GC_REQUEST_CHANGE_LANGUAGE = 140,
		HEADER_GC_RECV_LANGUAGE = 141,
#endif
	HEADER_GC_AUTH_SUCCESS = 150,
#ifdef ENABLE_SWITCHBOT
	HEADER_GC_SWITCHBOT = 171,
#endif
	HEADER_GC_AUTH_SUCCESS_OPENID = 154,
#ifdef TEXTS_IMPROVEMENT
	HEADER_GC_CHAT_NEW = 155,
#endif

#ifdef ENABLE_BATTLE_PASS
	HEADER_GC_BATTLE_PASS_OPEN = 160,
	HEADER_GC_BATTLE_PASS_UPDATE = 161,
	HEADER_GC_BATTLE_PASS_RANKING = 162,
#endif 
	// ROULETTE
	//HEADER_GC_ROULETTE = 200,
	// END_ROULETTE
	//
	HEADER_GC_SPECIFIC_EFFECT = 208,

	HEADER_GC_DRAGON_SOUL_REFINE = 209,
	HEADER_GC_RESPOND_CHANNELSTATUS = 210,



#ifdef __ENABLE_NEW_OFFLINESHOP__
	HEADER_GC_NEW_OFFLINESHOP = 214,
#endif

#ifdef ENABLE_ACCE_SYSTEM
	HEADER_GC_ACCE = 215,
#endif


#ifdef ENABLE_CUBE_RENEWAL_WORLDARD
	HEADER_GC_CUBE_RENEWAL = 217,
#endif

	HEADER_GC_RANKING_SEND = 218,
#ifdef ENABLE_ATLAS_BOSS
	HEADER_GC_BOSS_POSITION = 222,
#endif
#ifdef ENABLE_NEW_FISHING_SYSTEM
	HEADER_GC_FISHING_NEW = 223,
#endif

	HEADER_GC_MOUNT_INVENTORY = 224,

};
