#pragma once
#include "../service.h"
#include "../CommonDefines.h"

enum HEADER_CG
{
	HEADER_CG_HANDSHAKE = 0xf0,
	HEADER_CG_PONG = 0xef,
	HEADER_CG_TIME_SYNC = 0xed,
	HEADER_CG_KEY_AGREEMENT = 0xec,

	HEADER_CG_LOGIN = 0x20,
	HEADER_CG_ATTACK = 49,
	HEADER_CG_CHAT = 3,
	HEADER_CG_CHARACTER_CREATE = 0x19,
	HEADER_CG_CHARACTER_DELETE = 5,
	HEADER_CG_CHARACTER_SELECT = 6,
	HEADER_CG_MOVE = 7,
	HEADER_CG_SYNC_POSITION = 8,
	HEADER_CG_ENTERGAME = 10,

	HEADER_CG_ITEM_USE = 11,
	HEADER_CG_ITEM_DROP = 12,
	HEADER_CG_ITEM_MOVE = 13,
	HEADER_CG_ITEM_PICKUP = 15,

	HEADER_CG_QUICKSLOT_ADD = 16,
	HEADER_CG_QUICKSLOT_DEL = 17,
	HEADER_CG_QUICKSLOT_SWAP = 18,
	HEADER_CG_WHISPER = 19,
	HEADER_CG_ITEM_DROP2 = 20,
	HEADER_CG_ITEM_DESTROY = 21,
	HEADER_CG_ITEM_DIVISION = 22,
#ifdef __ENABLE_EXTEND_INVEN_SYSTEM__
	ENVANTER_BLACK = 23,
#endif

	HEADER_CG_ON_CLICK = 26,
	HEADER_CG_EXCHANGE = 27,
	HEADER_CG_CHARACTER_POSITION = 28,
	HEADER_CG_SCRIPT_ANSWER = 29,
	HEADER_CG_QUEST_INPUT_STRING = 30,
	HEADER_CG_QUEST_CONFIRM = 31,

#ifdef ENABLE_BATTLE_PASS
	HEADER_CG_BATTLE_PASS = 40,
#endif

	HEADER_CG_LOGIN3 = 44,
	HEADER_CG_SHOP = 50,
	HEADER_CG_FLY_TARGETING = 51,
	HEADER_CG_USE_SKILL = 42,
	HEADER_CG_ADD_FLY_TARGETING = 53,
	HEADER_CG_SHOOT = 54,
	HEADER_CG_MYSHOP = 55,

#ifdef __SKILL_COLOR_SYSTEM__
	HEADER_CG_SKILL_COLOR = 56,
#endif
#ifdef ENABLE_OPENSHOP_PACKET
	HEADER_CG_OPENSHOP = 57,
#endif
	HEADER_CG_ITEM_USE_TO_ITEM = 60,
	HEADER_CG_TARGET = 61,
	//HEADER_CG_TEXT = 64,
	HEADER_CG_WARP = 65,
	HEADER_CG_SCRIPT_BUTTON = 66,
	HEADER_CG_MESSENGER = 67,

	HEADER_CG_MALL_CHECKOUT = 69,
	HEADER_CG_SAFEBOX_CHECKIN = 70,
	HEADER_CG_SAFEBOX_CHECKOUT = 71,

	HEADER_CG_PARTY_INVITE = 72,
	HEADER_CG_PARTY_INVITE_ANSWER = 73,
	HEADER_CG_PARTY_REMOVE = 74,
	HEADER_CG_PARTY_SET_STATE = 75,
	HEADER_CG_PARTY_USE_SKILL = 76,
	HEADER_CG_SAFEBOX_ITEM_MOVE = 77,
	HEADER_CG_PARTY_PARAMETER = 78,

	HEADER_CG_GUILD = 80,
	HEADER_CG_ANSWER_MAKE_GUILD = 81,

	HEADER_CG_FISHING = 82,

	HEADER_CG_ITEM_GIVE = 83,
	HEADER_CG_EMPIRE = 90,

	HEADER_CG_REFINE = 96,

	HEADER_CG_MARK_LOGIN = 100,
	HEADER_CG_MARK_CRCLIST = 101,
	HEADER_CG_MARK_UPLOAD = 102,
	HEADER_CG_MARK_IDXLIST = 104,

	HEADER_CG_HACK = 105,
	HEADER_CG_CHANGE_NAME = 106,
	HEADER_CG_LOGIN2 = 109,
	HEADER_CG_DUNGEON = 110,
	HEADER_CG_GUILD_SYMBOL_UPLOAD = 112,
	HEADER_CG_SYMBOL_CRC = 113,

	HEADER_CG_SCRIPT_SELECT_ITEM = 114,
	HEADER_CG_LOGIN5_OPENID = 116,
#ifdef ENABLE_MAP_TELEPORTER
	HEADER_CG_MAP_TELEPORTER = 117,
#endif
#ifdef __ENABLE_NEW_OFFLINESHOP__
	HEADER_CG_NEW_OFFLINESHOP = 119,
#endif
#ifdef ENABLE_MULTI_LANGUAGE
	HEADER_CG_CHANGE_LANGUAGE = 120,
	HEADER_CG_REQUEST_LANGUAGE = 121,
#endif

	HEADER_CG_MOUNT_INVENTORY_CHECKIN = 125,
	HEADER_CG_MOUNT_INVENTORY_CHECKOUT = 126,
	HEADER_CG_MOUNT_INVENTORY_ITEM_MOVE = 127,

#ifdef __NEWPET_SYSTEM__
	HEADER_CG_PetSetName = 146,
#endif
 
#ifdef ENABLE_SWITCHBOT
	HEADER_CG_SWITCHBOT = 171,
#endif


	

#ifdef ENABLE_WHISPER_ADMIN_SYSTEM
	HEADER_CG_WHISPER_ADMIN = 220,
#endif
#ifdef __SEND_TARGET_INFO__
	HEADER_CG_TARGET_INFO_LOAD = 59,
#endif




	HEADER_CG_DRAGON_SOUL_REFINE = 205,
	HEADER_CG_STATE_CHECKER = 206,
#ifdef ENABLE_DS_REFINE_ALL
	HEADER_CG_DRAGON_SOUL_REFINE_ALL = 207,
#endif
#ifdef ENABLE_ACCE_SYSTEM
		HEADER_CG_ACCE = 211,
#endif
#ifdef ENABLE_CUBE_RENEWAL_WORLDARD
	HEADER_CG_CUBE_RENEWAL = 215,
#endif
#ifdef ENABLE_NEW_FISHING_SYSTEM
	HEADER_CG_FISHING_NEW = 216,
#endif

#if defined(ENABLE_CHRISTMAS_WHEEL_OF_DESTINY)
		HEADER_CG_WHEEL_DESTINY = 219,
#endif
	HEADER_CG_CLIENT_VERSION = 0xfd,
	HEADER_CG_CLIENT_VERSION2 = 0xf1,
};

enum SUB_HEADER_CG
{
	
};