if (MSVC)
	add_subdirectory(Launcher)
	add_subdirectory(3rd/F_FS)
	add_subdirectory(3rd/Granny)
	add_subdirectory(3rd/SpeedTree)

	add_subdirectory(Tools/Mysql2Proto/Mysql2Proto)
	add_subdirectory(Tools/MSAMaker)
	add_subdirectory(Tools/IXAC)
	add_subdirectory(Tools/IXAC_Updater)
endif()

add_subdirectory(Tools/QC)
#add_subdirectory(Tools/ServerAttrTool)
add_subdirectory(Server)
add_subdirectory(3rd/LUA)
#add_subdirectory(Tools)