message("Adding SpeedTreeRT lib")
add_library(SpeedTreeRT STATIC IMPORTED GLOBAL)

set(SPEEDTREE_LIBARY_PATH "")
set(SPEEDTREE_LIBARY_PATH ${CMAKE_CURRENT_LIST_DIR}\\SpeedTreeRT.lib)


set_target_properties(SpeedTreeRT PROPERTIES
	IMPORTED_LOCATION ${SPEEDTREE_LIBARY_PATH}
	#INTERFACE_COMPILE_DEFINITIONS "BUILDING_SPEEDTREE_STATIC=1"
	INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_CURRENT_LIST_DIR}
)